//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.23 at 10:31:42 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.crit.rai.it/prestoprime/rights/rightsindex", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.prestoprime.model.ext.rights;

