//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.23 at 10:31:42 PM CEST 
//

package eu.prestoprime.model.ext.rights;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aipId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rightsId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="owlFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "aipId", "rightsId", "owlFile" })
@XmlRootElement(name = "RightsModel", namespace = "http://www.prestoprime.eu/xsd/rightsmodel")
public class RightsModel implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(namespace = "http://www.prestoprime.eu/xsd/rightsmodel", required = true)
	protected String aipId;
	@XmlElement(namespace = "http://www.prestoprime.eu/xsd/rightsmodel", required = true)
	protected String rightsId;
	@XmlElement(namespace = "http://www.prestoprime.eu/xsd/rightsmodel", required = true)
	protected byte[] owlFile;

	/**
	 * Gets the value of the aipId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAipId() {
		return aipId;
	}

	/**
	 * Sets the value of the aipId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAipId(String value) {
		this.aipId = value;
	}

	/**
	 * Gets the value of the rightsId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRightsId() {
		return rightsId;
	}

	/**
	 * Sets the value of the rightsId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRightsId(String value) {
		this.rightsId = value;
	}

	/**
	 * Gets the value of the owlFile property.
	 * 
	 * @return possible object is byte[]
	 */
	public byte[] getOwlFile() {
		return owlFile;
	}

	/**
	 * Sets the value of the owlFile property.
	 * 
	 * @param value
	 *            allowed object is byte[]
	 */
	public void setOwlFile(byte[] value) {
		this.owlFile = value;
	}

}
