//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 06:00:06 PM CET 
//


package eu.prestoprime.premis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventOutcomeDetailComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eventOutcomeDetailComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{info:lc/xmlns/premis-v2}eventOutcomeDetailNote"/>
 *           &lt;element ref="{info:lc/xmlns/premis-v2}eventOutcomeDetailExtension" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{info:lc/xmlns/premis-v2}mdSec" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{info:lc/xmlns/premis-v2}eventOutcomeDetailExtension"/>
 *           &lt;element ref="{info:lc/xmlns/premis-v2}mdSec"/>
 *         &lt;/choice>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventOutcomeDetailComplexType", propOrder = {
    "eventOutcomeDetailNote",
    "eventOutcomeDetailExtension",
    "mdSec",
    "eventOutcomeDetailExtensionOrMdSec"
})
public class EventOutcomeDetailComplexType {

    protected String eventOutcomeDetailNote;
    protected List<ExtensionComplexType> eventOutcomeDetailExtension;
    protected List<MdSecDefinition> mdSec;
    @XmlElements({
        @XmlElement(name = "eventOutcomeDetailExtension", type = ExtensionComplexType.class),
        @XmlElement(name = "mdSec", type = MdSecDefinition.class)
    })
    protected List<Object> eventOutcomeDetailExtensionOrMdSec;

    /**
     * Gets the value of the eventOutcomeDetailNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventOutcomeDetailNote() {
        return eventOutcomeDetailNote;
    }

    /**
     * Sets the value of the eventOutcomeDetailNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventOutcomeDetailNote(String value) {
        this.eventOutcomeDetailNote = value;
    }

    /**
     * Gets the value of the eventOutcomeDetailExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventOutcomeDetailExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventOutcomeDetailExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionComplexType }
     * 
     * 
     */
    public List<ExtensionComplexType> getEventOutcomeDetailExtension() {
        if (eventOutcomeDetailExtension == null) {
            eventOutcomeDetailExtension = new ArrayList<ExtensionComplexType>();
        }
        return this.eventOutcomeDetailExtension;
    }

    /**
     * Gets the value of the mdSec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mdSec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMdSec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MdSecDefinition }
     * 
     * 
     */
    public List<MdSecDefinition> getMdSec() {
        if (mdSec == null) {
            mdSec = new ArrayList<MdSecDefinition>();
        }
        return this.mdSec;
    }

    /**
     * Gets the value of the eventOutcomeDetailExtensionOrMdSec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventOutcomeDetailExtensionOrMdSec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventOutcomeDetailExtensionOrMdSec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionComplexType }
     * {@link MdSecDefinition }
     * 
     * 
     */
    public List<Object> getEventOutcomeDetailExtensionOrMdSec() {
        if (eventOutcomeDetailExtensionOrMdSec == null) {
            eventOutcomeDetailExtensionOrMdSec = new ArrayList<Object>();
        }
        return this.eventOutcomeDetailExtensionOrMdSec;
    }

}
