//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 06:00:06 PM CET 
//


package eu.prestoprime.premis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for mdWrapDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mdWrapDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}binData" minOccurs="0"/>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}xmlData" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{info:lc/xmlns/premis-v2}metadataAttributeGroup"/>
 *       &lt;attGroup ref="{info:lc/xmlns/premis-v2}filecoreAttributeGroup"/>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mdWrapDefinition", propOrder = {
    "binData",
    "xmlData"
})
public class MdWrapDefinition {

    protected byte[] binData;
    protected XmlDataDefinition xmlData;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "LABEL")
    protected String label;
    @XmlAttribute(name = "MDTYPE", required = true)
    protected MDTYPEDefinition mdtype;
    @XmlAttribute(name = "OTHERMDTYPE")
    protected String othermdtype;
    @XmlAttribute(name = "MDTYPEVERSION")
    protected String mdtypeversion;
    @XmlAttribute(name = "MIMETYPE")
    protected String mimetype;
    @XmlAttribute(name = "SIZE")
    protected Long size;
    @XmlAttribute(name = "CREATED")
    protected String created;
    @XmlAttribute(name = "CHECKSUM")
    protected String checksum;
    @XmlAttribute(name = "CHECKSUMTYPE")
    protected CHECKSUMTYPEDefinition checksumtype;

    /**
     * Gets the value of the binData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBinData() {
        return binData;
    }

    /**
     * Sets the value of the binData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBinData(byte[] value) {
        this.binData = value;
    }

    /**
     * Gets the value of the xmlData property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDataDefinition }
     *     
     */
    public XmlDataDefinition getXmlData() {
        return xmlData;
    }

    /**
     * Sets the value of the xmlData property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDataDefinition }
     *     
     */
    public void setXmlData(XmlDataDefinition value) {
        this.xmlData = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLABEL() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLABEL(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the mdtype property.
     * 
     * @return
     *     possible object is
     *     {@link MDTYPEDefinition }
     *     
     */
    public MDTYPEDefinition getMDTYPE() {
        return mdtype;
    }

    /**
     * Sets the value of the mdtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDTYPEDefinition }
     *     
     */
    public void setMDTYPE(MDTYPEDefinition value) {
        this.mdtype = value;
    }

    /**
     * Gets the value of the othermdtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTHERMDTYPE() {
        return othermdtype;
    }

    /**
     * Sets the value of the othermdtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTHERMDTYPE(String value) {
        this.othermdtype = value;
    }

    /**
     * Gets the value of the mdtypeversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMDTYPEVERSION() {
        return mdtypeversion;
    }

    /**
     * Sets the value of the mdtypeversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMDTYPEVERSION(String value) {
        this.mdtypeversion = value;
    }

    /**
     * Gets the value of the mimetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIMETYPE() {
        return mimetype;
    }

    /**
     * Sets the value of the mimetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIMETYPE(String value) {
        this.mimetype = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSIZE() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSIZE(Long value) {
        this.size = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREATED() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREATED(String value) {
        this.created = value;
    }

    /**
     * Gets the value of the checksum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHECKSUM() {
        return checksum;
    }

    /**
     * Sets the value of the checksum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHECKSUM(String value) {
        this.checksum = value;
    }

    /**
     * Gets the value of the checksumtype property.
     * 
     * @return
     *     possible object is
     *     {@link CHECKSUMTYPEDefinition }
     *     
     */
    public CHECKSUMTYPEDefinition getCHECKSUMTYPE() {
        return checksumtype;
    }

    /**
     * Sets the value of the checksumtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHECKSUMTYPEDefinition }
     *     
     */
    public void setCHECKSUMTYPE(CHECKSUMTYPEDefinition value) {
        this.checksumtype = value;
    }

}
