//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 06:00:06 PM CET 
//


package eu.prestoprime.premis;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relationshipComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relationshipComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}relationshipType"/>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}relationshipSubType"/>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}relatedObjectIdentification" maxOccurs="unbounded"/>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}relatedEventIdentification" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relationshipComplexType", propOrder = {
    "relationshipType",
    "relationshipSubType",
    "relatedObjectIdentification",
    "relatedEventIdentification"
})
public class RelationshipComplexType {

    @XmlElement(required = true)
    protected String relationshipType;
    @XmlElement(required = true)
    protected String relationshipSubType;
    @XmlElement(required = true)
    protected List<RelatedObjectIdentificationComplexType> relatedObjectIdentification;
    protected List<RelatedEventIdentificationComplexType> relatedEventIdentification;

    /**
     * Gets the value of the relationshipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipType() {
        return relationshipType;
    }

    /**
     * Sets the value of the relationshipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipType(String value) {
        this.relationshipType = value;
    }

    /**
     * Gets the value of the relationshipSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipSubType() {
        return relationshipSubType;
    }

    /**
     * Sets the value of the relationshipSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipSubType(String value) {
        this.relationshipSubType = value;
    }

    /**
     * Gets the value of the relatedObjectIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedObjectIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedObjectIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedObjectIdentificationComplexType }
     * 
     * 
     */
    public List<RelatedObjectIdentificationComplexType> getRelatedObjectIdentification() {
        if (relatedObjectIdentification == null) {
            relatedObjectIdentification = new ArrayList<RelatedObjectIdentificationComplexType>();
        }
        return this.relatedObjectIdentification;
    }

    /**
     * Gets the value of the relatedEventIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedEventIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedEventIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedEventIdentificationComplexType }
     * 
     * 
     */
    public List<RelatedEventIdentificationComplexType> getRelatedEventIdentification() {
        if (relatedEventIdentification == null) {
            relatedEventIdentification = new ArrayList<RelatedEventIdentificationComplexType>();
        }
        return this.relatedEventIdentification;
    }

}
