//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 06:00:06 PM CET 
//


package eu.prestoprime.premis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statuteDocumentationIdentifierComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statuteDocumentationIdentifierComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}statuteDocumentationIdentifierType"/>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}statuteDocumentationIdentifierValue"/>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}statuteDocumentationRole" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statuteDocumentationIdentifierComplexType", propOrder = {
    "statuteDocumentationIdentifierType",
    "statuteDocumentationIdentifierValue",
    "statuteDocumentationRole"
})
public class StatuteDocumentationIdentifierComplexType {

    @XmlElement(required = true)
    protected String statuteDocumentationIdentifierType;
    @XmlElement(required = true)
    protected String statuteDocumentationIdentifierValue;
    protected String statuteDocumentationRole;

    /**
     * Gets the value of the statuteDocumentationIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatuteDocumentationIdentifierType() {
        return statuteDocumentationIdentifierType;
    }

    /**
     * Sets the value of the statuteDocumentationIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatuteDocumentationIdentifierType(String value) {
        this.statuteDocumentationIdentifierType = value;
    }

    /**
     * Gets the value of the statuteDocumentationIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatuteDocumentationIdentifierValue() {
        return statuteDocumentationIdentifierValue;
    }

    /**
     * Sets the value of the statuteDocumentationIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatuteDocumentationIdentifierValue(String value) {
        this.statuteDocumentationIdentifierValue = value;
    }

    /**
     * Gets the value of the statuteDocumentationRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatuteDocumentationRole() {
        return statuteDocumentationRole;
    }

    /**
     * Sets the value of the statuteDocumentationRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatuteDocumentationRole(String value) {
        this.statuteDocumentationRole = value;
    }

}
