//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.04 at 11:30:52 PM CEST 
//

package eu.prestoprime.model.workflow;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for wfType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="wfType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ingest"/>
 *     &lt;enumeration value="update"/>
 *     &lt;enumeration value="access"/>
 *     &lt;enumeration value="action"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "wfType")
@XmlEnum
public enum WfType {

	@XmlEnumValue("ingest")
	INGEST("ingest"), @XmlEnumValue("update")
	UPDATE("update"), @XmlEnumValue("access")
	ACCESS("access"), @XmlEnumValue("action")
	ACTION("action");
	private final String value;

	WfType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static WfType fromValue(String v) {
		for (WfType c : WfType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
