//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.08 at 11:57:42 AM MEZ 
//

package eu.prestoprime.model.search;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="params">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="query" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="resultCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                   &lt;element name="sortField" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sortAscending" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="selectedFacets">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="selectedFacet" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="facetName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="filterQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="hits">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="hit" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;sequence>
 *                               &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;sequence>
 *                               &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;sequence>
 *                               &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;sequence>
 *                               &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;sequence>
 *                               &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;sequence>
 *                               &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;sequence>
 *                               &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;sequence>
 *                               &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;sequence>
 *                               &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;sequence>
 *                               &lt;element name="userAnnot" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;/sequence>
 *                             &lt;element name="aspectRat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="codec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="pos" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="createDate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="total" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="facets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="facet" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="value" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="term" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                                     &lt;attribute name="filterQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="selected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="facetName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "errorMessage", "params", "hits", "facets" })
@XmlRootElement(name = "searchResults")
public class SearchResults {

	@XmlElement(required = true)
	protected String errorMessage;
	@XmlElement(required = true)
	protected SearchResults.Params params;
	@XmlElement(required = true)
	protected SearchResults.Hits hits;
	@XmlElement(required = true)
	protected SearchResults.Facets facets;

	/**
	 * Gets the value of the errorMessage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getErrorMessage() {
		return errorMessage;
	}

	/**
	 * Sets the value of the errorMessage property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setErrorMessage(String value) {
		this.errorMessage = value;
	}

	/**
	 * Gets the value of the params property.
	 * 
	 * @return possible object is {@link SearchResults.Params }
	 * 
	 */
	public SearchResults.Params getParams() {
		return params;
	}

	/**
	 * Sets the value of the params property.
	 * 
	 * @param value
	 *            allowed object is {@link SearchResults.Params }
	 * 
	 */
	public void setParams(SearchResults.Params value) {
		this.params = value;
	}

	/**
	 * Gets the value of the hits property.
	 * 
	 * @return possible object is {@link SearchResults.Hits }
	 * 
	 */
	public SearchResults.Hits getHits() {
		return hits;
	}

	/**
	 * Sets the value of the hits property.
	 * 
	 * @param value
	 *            allowed object is {@link SearchResults.Hits }
	 * 
	 */
	public void setHits(SearchResults.Hits value) {
		this.hits = value;
	}

	/**
	 * Gets the value of the facets property.
	 * 
	 * @return possible object is {@link SearchResults.Facets }
	 * 
	 */
	public SearchResults.Facets getFacets() {
		return facets;
	}

	/**
	 * Sets the value of the facets property.
	 * 
	 * @param value
	 *            allowed object is {@link SearchResults.Facets }
	 * 
	 */
	public void setFacets(SearchResults.Facets value) {
		this.facets = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="facet" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="value" maxOccurs="unbounded">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="term" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
	 *                           &lt;attribute name="filterQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="selected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="facetName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "facet" })
	public static class Facets {

		protected List<SearchResults.Facets.Facet> facet;

		/**
		 * Gets the value of the facet property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the facet property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getFacet().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link SearchResults.Facets.Facet }
		 * 
		 * 
		 */
		public List<SearchResults.Facets.Facet> getFacet() {
			if (facet == null) {
				facet = new ArrayList<SearchResults.Facets.Facet>();
			}
			return this.facet;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="value" maxOccurs="unbounded">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="term" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
		 *                 &lt;attribute name="filterQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="selected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="facetName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "value" })
		public static class Facet {

			@XmlElement(required = true)
			protected List<SearchResults.Facets.Facet.Value> value;
			@XmlAttribute
			@XmlSchemaType(name = "anySimpleType")
			protected String facetName;

			/**
			 * Gets the value of the value property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the value property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getValue().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link SearchResults.Facets.Facet.Value }
			 * 
			 * 
			 */
			public List<SearchResults.Facets.Facet.Value> getValue() {
				if (value == null) {
					value = new ArrayList<SearchResults.Facets.Facet.Value>();
				}
				return this.value;
			}

			/**
			 * Gets the value of the facetName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFacetName() {
				return facetName;
			}

			/**
			 * Sets the value of the facetName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setFacetName(String value) {
				this.facetName = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="term" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="count" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
			 *       &lt;attribute name="filterQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="selected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class Value {

				@XmlAttribute(required = true)
				protected String term;
				@XmlAttribute(required = true)
				@XmlSchemaType(name = "unsignedInt")
				protected long count;
				@XmlAttribute(required = true)
				protected String filterQuery;
				@XmlAttribute
				protected Boolean selected;

				/**
				 * Gets the value of the term property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getTerm() {
					return term;
				}

				/**
				 * Sets the value of the term property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setTerm(String value) {
					this.term = value;
				}

				/**
				 * Gets the value of the count property.
				 * 
				 */
				public long getCount() {
					return count;
				}

				/**
				 * Sets the value of the count property.
				 * 
				 */
				public void setCount(long value) {
					this.count = value;
				}

				/**
				 * Gets the value of the filterQuery property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getFilterQuery() {
					return filterQuery;
				}

				/**
				 * Sets the value of the filterQuery property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setFilterQuery(String value) {
					this.filterQuery = value;
				}

				/**
				 * Gets the value of the selected property.
				 * 
				 * @return possible object is {@link Boolean }
				 * 
				 */
				public Boolean isSelected() {
					return selected;
				}

				/**
				 * Sets the value of the selected property.
				 * 
				 * @param value
				 *            allowed object is {@link Boolean }
				 * 
				 */
				public void setSelected(Boolean value) {
					this.selected = value;
				}

			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="hit" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;sequence>
	 *                     &lt;element name="userAnnot" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                   &lt;/sequence>
	 *                   &lt;element name="aspectRat" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                   &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="codec" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="pos" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="createDate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="total" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "hit" })
	public static class Hits {

		protected List<SearchResults.Hits.Hit> hit;
		@XmlAttribute(required = true)
		@XmlSchemaType(name = "unsignedInt")
		protected long total;

		/**
		 * Gets the value of the hit property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the hit property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getHit().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link SearchResults.Hits.Hit }
		 * 
		 * 
		 */
		public List<SearchResults.Hits.Hit> getHit() {
			if (hit == null) {
				hit = new ArrayList<SearchResults.Hits.Hit>();
			}
			return this.hit;
		}

		/**
		 * Gets the value of the total property.
		 * 
		 */
		public long getTotal() {
			return total;
		}

		/**
		 * Sets the value of the total property.
		 * 
		 */
		public void setTotal(long value) {
			this.total = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;sequence>
		 *           &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;sequence>
		 *           &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;sequence>
		 *           &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;sequence>
		 *           &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;sequence>
		 *           &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;sequence>
		 *           &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;sequence>
		 *           &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;sequence>
		 *           &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;sequence>
		 *           &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;sequence>
		 *           &lt;element name="userAnnot" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *         &lt;/sequence>
		 *         &lt;element name="aspectRat" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *         &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="codec" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="pos" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="createDate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "title", "creator", "date", "publisher", "description", "format", "identifier", "language", "subject", "userAnnot", "aspectRat", "width", "height", "resolution", "codec", "duration" })
		public static class Hit {

			protected List<String> title;
			protected List<String> creator;
			protected List<String> date;
			protected List<String> publisher;
			protected List<String> description;
			protected List<String> format;
			protected List<String> identifier;
			protected List<String> language;
			protected List<String> subject;
			protected List<String> userAnnot;
			@XmlElement(required = true)
			protected String aspectRat;
			protected int width;
			protected int height;
			@XmlElement(required = true)
			protected String resolution;
			@XmlElement(required = true)
			protected String codec;
			protected float duration;
			@XmlAttribute(required = true)
			protected String id;
			@XmlAttribute(required = true)
			protected String pos;
			@XmlAttribute(required = true)
			protected String createDate;

			/**
			 * Gets the value of the title property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the title property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getTitle().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getTitle() {
				if (title == null) {
					title = new ArrayList<String>();
				}
				return this.title;
			}

			/**
			 * Gets the value of the creator property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the creator property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getCreator().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getCreator() {
				if (creator == null) {
					creator = new ArrayList<String>();
				}
				return this.creator;
			}

			/**
			 * Gets the value of the date property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the date property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getDate().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getDate() {
				if (date == null) {
					date = new ArrayList<String>();
				}
				return this.date;
			}

			/**
			 * Gets the value of the publisher property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the publisher property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getPublisher().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getPublisher() {
				if (publisher == null) {
					publisher = new ArrayList<String>();
				}
				return this.publisher;
			}

			/**
			 * Gets the value of the description property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the description property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getDescription().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getDescription() {
				if (description == null) {
					description = new ArrayList<String>();
				}
				return this.description;
			}

			/**
			 * Gets the value of the format property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the format property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getFormat().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getFormat() {
				if (format == null) {
					format = new ArrayList<String>();
				}
				return this.format;
			}

			/**
			 * Gets the value of the identifier property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the identifier property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getIdentifier().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getIdentifier() {
				if (identifier == null) {
					identifier = new ArrayList<String>();
				}
				return this.identifier;
			}

			/**
			 * Gets the value of the language property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the language property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getLanguage().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getLanguage() {
				if (language == null) {
					language = new ArrayList<String>();
				}
				return this.language;
			}

			/**
			 * Gets the value of the subject property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the subject property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getSubject().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getSubject() {
				if (subject == null) {
					subject = new ArrayList<String>();
				}
				return this.subject;
			}

			/**
			 * Gets the value of the userAnnot property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the userAnnot property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getUserAnnot().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link String }
			 * 
			 * 
			 */
			public List<String> getUserAnnot() {
				if (userAnnot == null) {
					userAnnot = new ArrayList<String>();
				}
				return this.userAnnot;
			}

			/**
			 * Gets the value of the aspectRat property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getAspectRat() {
				return aspectRat;
			}

			/**
			 * Sets the value of the aspectRat property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setAspectRat(String value) {
				this.aspectRat = value;
			}

			/**
			 * Gets the value of the width property.
			 * 
			 */
			public int getWidth() {
				return width;
			}

			/**
			 * Sets the value of the width property.
			 * 
			 */
			public void setWidth(int value) {
				this.width = value;
			}

			/**
			 * Gets the value of the height property.
			 * 
			 */
			public int getHeight() {
				return height;
			}

			/**
			 * Sets the value of the height property.
			 * 
			 */
			public void setHeight(int value) {
				this.height = value;
			}

			/**
			 * Gets the value of the resolution property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getResolution() {
				return resolution;
			}

			/**
			 * Sets the value of the resolution property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setResolution(String value) {
				this.resolution = value;
			}

			/**
			 * Gets the value of the codec property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCodec() {
				return codec;
			}

			/**
			 * Sets the value of the codec property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCodec(String value) {
				this.codec = value;
			}

			/**
			 * Gets the value of the duration property.
			 * 
			 */
			public float getDuration() {
				return duration;
			}

			/**
			 * Sets the value of the duration property.
			 * 
			 */
			public void setDuration(float value) {
				this.duration = value;
			}

			/**
			 * Gets the value of the id property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getId() {
				return id;
			}

			/**
			 * Sets the value of the id property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setId(String value) {
				this.id = value;
			}

			/**
			 * Gets the value of the pos property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPos() {
				return pos;
			}

			/**
			 * Sets the value of the pos property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPos(String value) {
				this.pos = value;
			}

			/**
			 * Gets the value of the createDate property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCreateDate() {
				return createDate;
			}

			/**
			 * Sets the value of the createDate property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCreateDate(String value) {
				this.createDate = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="query" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
	 *         &lt;element name="resultCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
	 *         &lt;element name="sortField" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="sortAscending" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
	 *         &lt;element name="selectedFacets">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="selectedFacet" maxOccurs="unbounded" minOccurs="0">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *                           &lt;/sequence>
	 *                           &lt;attribute name="facetName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="filterQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "query", "from", "resultCount", "sortField", "sortAscending", "selectedFacets" })
	public static class Params {

		@XmlElement(required = true)
		protected String query;
		@XmlSchemaType(name = "unsignedInt")
		protected long from;
		@XmlSchemaType(name = "unsignedInt")
		protected long resultCount;
		@XmlElement(required = true)
		protected String sortField;
		protected boolean sortAscending;
		@XmlElement(required = true)
		protected SearchResults.Params.SelectedFacets selectedFacets;

		/**
		 * Gets the value of the query property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getQuery() {
			return query;
		}

		/**
		 * Sets the value of the query property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setQuery(String value) {
			this.query = value;
		}

		/**
		 * Gets the value of the from property.
		 * 
		 */
		public long getFrom() {
			return from;
		}

		/**
		 * Sets the value of the from property.
		 * 
		 */
		public void setFrom(long value) {
			this.from = value;
		}

		/**
		 * Gets the value of the resultCount property.
		 * 
		 */
		public long getResultCount() {
			return resultCount;
		}

		/**
		 * Sets the value of the resultCount property.
		 * 
		 */
		public void setResultCount(long value) {
			this.resultCount = value;
		}

		/**
		 * Gets the value of the sortField property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSortField() {
			return sortField;
		}

		/**
		 * Sets the value of the sortField property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSortField(String value) {
			this.sortField = value;
		}

		/**
		 * Gets the value of the sortAscending property.
		 * 
		 */
		public boolean isSortAscending() {
			return sortAscending;
		}

		/**
		 * Sets the value of the sortAscending property.
		 * 
		 */
		public void setSortAscending(boolean value) {
			this.sortAscending = value;
		}

		/**
		 * Gets the value of the selectedFacets property.
		 * 
		 * @return possible object is
		 *         {@link SearchResults.Params.SelectedFacets }
		 * 
		 */
		public SearchResults.Params.SelectedFacets getSelectedFacets() {
			return selectedFacets;
		}

		/**
		 * Sets the value of the selectedFacets property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link SearchResults.Params.SelectedFacets }
		 * 
		 */
		public void setSelectedFacets(SearchResults.Params.SelectedFacets value) {
			this.selectedFacets = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="selectedFacet" maxOccurs="unbounded" minOccurs="0">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
		 *                 &lt;/sequence>
		 *                 &lt;attribute name="facetName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="filterQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "selectedFacet" })
		public static class SelectedFacets {

			protected List<SearchResults.Params.SelectedFacets.SelectedFacet> selectedFacet;

			/**
			 * Gets the value of the selectedFacet property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the selectedFacet property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getSelectedFacet().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link SearchResults.Params.SelectedFacets.SelectedFacet }
			 * 
			 * 
			 */
			public List<SearchResults.Params.SelectedFacets.SelectedFacet> getSelectedFacet() {
				if (selectedFacet == null) {
					selectedFacet = new ArrayList<SearchResults.Params.SelectedFacets.SelectedFacet>();
				}
				return this.selectedFacet;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
			 *       &lt;/sequence>
			 *       &lt;attribute name="facetName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="filterQuery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "value" })
			public static class SelectedFacet {

				protected List<String> value;
				@XmlAttribute(required = true)
				protected String facetName;
				@XmlAttribute(required = true)
				protected String filterQuery;

				/**
				 * Gets the value of the value property.
				 * 
				 * <p>
				 * This accessor method returns a reference to the live list,
				 * not a snapshot. Therefore any modification you make to the
				 * returned list will be present inside the JAXB object. This is
				 * why there is not a <CODE>set</CODE> method for the value
				 * property.
				 * 
				 * <p>
				 * For example, to add a new item, do as follows:
				 * 
				 * <pre>
				 * getValue().add(newItem);
				 * </pre>
				 * 
				 * 
				 * <p>
				 * Objects of the following type(s) are allowed in the list
				 * {@link String }
				 * 
				 * 
				 */
				public List<String> getValue() {
					if (value == null) {
						value = new ArrayList<String>();
					}
					return this.value;
				}

				/**
				 * Gets the value of the facetName property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getFacetName() {
					return facetName;
				}

				/**
				 * Sets the value of the facetName property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setFacetName(String value) {
					this.facetName = value;
				}

				/**
				 * Gets the value of the filterQuery property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getFilterQuery() {
					return filterQuery;
				}

				/**
				 * Sets the value of the filterQuery property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setFilterQuery(String value) {
					this.filterQuery = value;
				}

			}

		}

	}

}
