//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.04 at 11:30:52 PM CEST 
//

package eu.prestoprime.model.datatypes;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the eu.prestoprime.model.datatypes package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: eu.prestoprime.model.datatypes
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Datatypes }
	 * 
	 */
	public Datatypes createDatatypes() {
		return new Datatypes();
	}

	/**
	 * Create an instance of {@link Datatype }
	 * 
	 */
	public Datatype createDatatype() {
		return new Datatype();
	}

	/**
	 * Create an instance of {@link Ref }
	 * 
	 */
	public Ref createRef() {
		return new Ref();
	}

	/**
	 * Create an instance of {@link Section }
	 * 
	 */
	public Section createSection() {
		return new Section();
	}

}
