//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AudioVisualSegmentType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AudioVisualSegmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}SegmentType">
 *       &lt;sequence>
 *         &lt;element name="MediaTime" type="{urn:mpeg:mpeg7:schema:2004}MediaTimeType"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="TemporalDecomposition" type="{urn:mpeg:mpeg7:schema:2004}AudioVisualSegmentTemporalDecompositionType"/>
 *           &lt;element name="MediaSourceDecomposition" type="{urn:mpeg:mpeg7:schema:2004}AudioVisualSegmentMediaSourceDecompositionType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AudioVisualSegmentType", propOrder = { "mediaTime", "temporalDecompositionOrMediaSourceDecomposition" })
public class AudioVisualSegmentType extends SegmentType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "MediaTime", required = true)
	protected MediaTimeType mediaTime;
	@XmlElements({ @XmlElement(name = "TemporalDecomposition", type = AudioVisualSegmentTemporalDecompositionType.class), @XmlElement(name = "MediaSourceDecomposition", type = AudioVisualSegmentMediaSourceDecompositionType.class) })
	protected List<SegmentDecompositionType> temporalDecompositionOrMediaSourceDecomposition;

	/**
	 * Gets the value of the mediaTime property.
	 * 
	 * @return possible object is {@link MediaTimeType }
	 * 
	 */
	public MediaTimeType getMediaTime() {
		return mediaTime;
	}

	/**
	 * Sets the value of the mediaTime property.
	 * 
	 * @param value
	 *            allowed object is {@link MediaTimeType }
	 * 
	 */
	public void setMediaTime(MediaTimeType value) {
		this.mediaTime = value;
	}

	/**
	 * Gets the value of the temporalDecompositionOrMediaSourceDecomposition
	 * property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the
	 * temporalDecompositionOrMediaSourceDecomposition property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTemporalDecompositionOrMediaSourceDecomposition().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link AudioVisualSegmentTemporalDecompositionType }
	 * {@link AudioVisualSegmentMediaSourceDecompositionType }
	 * 
	 * 
	 */
	public List<SegmentDecompositionType> getTemporalDecompositionOrMediaSourceDecomposition() {
		if (temporalDecompositionOrMediaSourceDecomposition == null) {
			temporalDecompositionOrMediaSourceDecomposition = new ArrayList<SegmentDecompositionType>();
		}
		return this.temporalDecompositionOrMediaSourceDecomposition;
	}

}
