//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AudioSummaryComponentType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AudioSummaryComponentType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}DType">
 *       &lt;sequence>
 *         &lt;element name="AudioSourceID" type="{urn:mpeg:mpeg7:schema:2004}UniqueIDType"/>
 *         &lt;element name="AudioSourceLocator" type="{urn:mpeg:mpeg7:schema:2004}TemporalSegmentLocatorType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AudioSummaryComponentType", propOrder = { "audioSourceID", "audioSourceLocator" })
public class AudioSummaryComponentType extends DType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "AudioSourceID", required = true)
	protected UniqueIDType audioSourceID;
	@XmlElement(name = "AudioSourceLocator", required = true)
	protected TemporalSegmentLocatorType audioSourceLocator;

	/**
	 * Gets the value of the audioSourceID property.
	 * 
	 * @return possible object is {@link UniqueIDType }
	 * 
	 */
	public UniqueIDType getAudioSourceID() {
		return audioSourceID;
	}

	/**
	 * Sets the value of the audioSourceID property.
	 * 
	 * @param value
	 *            allowed object is {@link UniqueIDType }
	 * 
	 */
	public void setAudioSourceID(UniqueIDType value) {
		this.audioSourceID = value;
	}

	/**
	 * Gets the value of the audioSourceLocator property.
	 * 
	 * @return possible object is {@link TemporalSegmentLocatorType }
	 * 
	 */
	public TemporalSegmentLocatorType getAudioSourceLocator() {
		return audioSourceLocator;
	}

	/**
	 * Sets the value of the audioSourceLocator property.
	 * 
	 * @param value
	 *            allowed object is {@link TemporalSegmentLocatorType }
	 * 
	 */
	public void setAudioSourceLocator(TemporalSegmentLocatorType value) {
		this.audioSourceLocator = value;
	}

}
