//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ColorLayoutType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ColorLayoutType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}VisualDType">
 *       &lt;sequence>
 *         &lt;element name="YDCCoeff" type="{urn:mpeg:mpeg7:schema:2004}unsigned6"/>
 *         &lt;element name="CbDCCoeff" type="{urn:mpeg:mpeg7:schema:2004}unsigned6"/>
 *         &lt;element name="CrDCCoeff" type="{urn:mpeg:mpeg7:schema:2004}unsigned6"/>
 *         &lt;choice>
 *           &lt;element name="YACCoeff2">
 *             &lt;simpleType>
 *               &lt;restriction>
 *                 &lt;simpleType>
 *                   &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                 &lt;/simpleType>
 *                 &lt;length value="2"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="YACCoeff5">
 *             &lt;simpleType>
 *               &lt;restriction>
 *                 &lt;simpleType>
 *                   &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                 &lt;/simpleType>
 *                 &lt;length value="5"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="YACCoeff9">
 *             &lt;simpleType>
 *               &lt;restriction>
 *                 &lt;simpleType>
 *                   &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                 &lt;/simpleType>
 *                 &lt;length value="9"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="YACCoeff14">
 *             &lt;simpleType>
 *               &lt;restriction>
 *                 &lt;simpleType>
 *                   &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                 &lt;/simpleType>
 *                 &lt;length value="14"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="YACCoeff20">
 *             &lt;simpleType>
 *               &lt;restriction>
 *                 &lt;simpleType>
 *                   &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                 &lt;/simpleType>
 *                 &lt;length value="20"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="YACCoeff27">
 *             &lt;simpleType>
 *               &lt;restriction>
 *                 &lt;simpleType>
 *                   &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                 &lt;/simpleType>
 *                 &lt;length value="27"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="YACCoeff63">
 *             &lt;simpleType>
 *               &lt;restriction>
 *                 &lt;simpleType>
 *                   &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                 &lt;/simpleType>
 *                 &lt;length value="63"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="CbACCoeff2">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="2"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *             &lt;element name="CrACCoeff2">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="2"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="CbACCoeff5">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *             &lt;element name="CrACCoeff5">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="CbACCoeff9">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="9"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *             &lt;element name="CrACCoeff9">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="9"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="CbACCoeff14">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="14"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *             &lt;element name="CrACCoeff14">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="14"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="CbACCoeff20">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="20"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *             &lt;element name="CrACCoeff20">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="20"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="CbACCoeff27">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="27"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *             &lt;element name="CrACCoeff27">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="27"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="CbACCoeff63">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="63"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *             &lt;element name="CrACCoeff63">
 *               &lt;simpleType>
 *                 &lt;restriction>
 *                   &lt;simpleType>
 *                     &lt;list itemType="{urn:mpeg:mpeg7:schema:2004}unsigned5" />
 *                   &lt;/simpleType>
 *                   &lt;length value="63"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColorLayoutType", propOrder = { "ydcCoeff", "cbDCCoeff", "crDCCoeff", "yacCoeff2", "yacCoeff5", "yacCoeff9", "yacCoeff14", "yacCoeff20", "yacCoeff27", "yacCoeff63", "cbACCoeff2", "crACCoeff2", "cbACCoeff5", "crACCoeff5", "cbACCoeff9", "crACCoeff9", "cbACCoeff14", "crACCoeff14", "cbACCoeff20", "crACCoeff20", "cbACCoeff27", "crACCoeff27", "cbACCoeff63", "crACCoeff63" })
public class ColorLayoutType extends VisualDType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "YDCCoeff")
	protected int ydcCoeff;
	@XmlElement(name = "CbDCCoeff")
	protected int cbDCCoeff;
	@XmlElement(name = "CrDCCoeff")
	protected int crDCCoeff;
	@XmlList
	@XmlElement(name = "YACCoeff2", type = Integer.class)
	protected List<Integer> yacCoeff2;
	@XmlList
	@XmlElement(name = "YACCoeff5", type = Integer.class)
	protected List<Integer> yacCoeff5;
	@XmlList
	@XmlElement(name = "YACCoeff9", type = Integer.class)
	protected List<Integer> yacCoeff9;
	@XmlList
	@XmlElement(name = "YACCoeff14", type = Integer.class)
	protected List<Integer> yacCoeff14;
	@XmlList
	@XmlElement(name = "YACCoeff20", type = Integer.class)
	protected List<Integer> yacCoeff20;
	@XmlList
	@XmlElement(name = "YACCoeff27", type = Integer.class)
	protected List<Integer> yacCoeff27;
	@XmlList
	@XmlElement(name = "YACCoeff63", type = Integer.class)
	protected List<Integer> yacCoeff63;
	@XmlList
	@XmlElement(name = "CbACCoeff2", type = Integer.class)
	protected List<Integer> cbACCoeff2;
	@XmlList
	@XmlElement(name = "CrACCoeff2", type = Integer.class)
	protected List<Integer> crACCoeff2;
	@XmlList
	@XmlElement(name = "CbACCoeff5", type = Integer.class)
	protected List<Integer> cbACCoeff5;
	@XmlList
	@XmlElement(name = "CrACCoeff5", type = Integer.class)
	protected List<Integer> crACCoeff5;
	@XmlList
	@XmlElement(name = "CbACCoeff9", type = Integer.class)
	protected List<Integer> cbACCoeff9;
	@XmlList
	@XmlElement(name = "CrACCoeff9", type = Integer.class)
	protected List<Integer> crACCoeff9;
	@XmlList
	@XmlElement(name = "CbACCoeff14", type = Integer.class)
	protected List<Integer> cbACCoeff14;
	@XmlList
	@XmlElement(name = "CrACCoeff14", type = Integer.class)
	protected List<Integer> crACCoeff14;
	@XmlList
	@XmlElement(name = "CbACCoeff20", type = Integer.class)
	protected List<Integer> cbACCoeff20;
	@XmlList
	@XmlElement(name = "CrACCoeff20", type = Integer.class)
	protected List<Integer> crACCoeff20;
	@XmlList
	@XmlElement(name = "CbACCoeff27", type = Integer.class)
	protected List<Integer> cbACCoeff27;
	@XmlList
	@XmlElement(name = "CrACCoeff27", type = Integer.class)
	protected List<Integer> crACCoeff27;
	@XmlList
	@XmlElement(name = "CbACCoeff63", type = Integer.class)
	protected List<Integer> cbACCoeff63;
	@XmlList
	@XmlElement(name = "CrACCoeff63", type = Integer.class)
	protected List<Integer> crACCoeff63;

	/**
	 * Gets the value of the ydcCoeff property.
	 * 
	 */
	public int getYDCCoeff() {
		return ydcCoeff;
	}

	/**
	 * Sets the value of the ydcCoeff property.
	 * 
	 */
	public void setYDCCoeff(int value) {
		this.ydcCoeff = value;
	}

	/**
	 * Gets the value of the cbDCCoeff property.
	 * 
	 */
	public int getCbDCCoeff() {
		return cbDCCoeff;
	}

	/**
	 * Sets the value of the cbDCCoeff property.
	 * 
	 */
	public void setCbDCCoeff(int value) {
		this.cbDCCoeff = value;
	}

	/**
	 * Gets the value of the crDCCoeff property.
	 * 
	 */
	public int getCrDCCoeff() {
		return crDCCoeff;
	}

	/**
	 * Sets the value of the crDCCoeff property.
	 * 
	 */
	public void setCrDCCoeff(int value) {
		this.crDCCoeff = value;
	}

	/**
	 * Gets the value of the yacCoeff2 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the yacCoeff2 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getYACCoeff2().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getYACCoeff2() {
		if (yacCoeff2 == null) {
			yacCoeff2 = new ArrayList<Integer>();
		}
		return this.yacCoeff2;
	}

	/**
	 * Gets the value of the yacCoeff5 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the yacCoeff5 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getYACCoeff5().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getYACCoeff5() {
		if (yacCoeff5 == null) {
			yacCoeff5 = new ArrayList<Integer>();
		}
		return this.yacCoeff5;
	}

	/**
	 * Gets the value of the yacCoeff9 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the yacCoeff9 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getYACCoeff9().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getYACCoeff9() {
		if (yacCoeff9 == null) {
			yacCoeff9 = new ArrayList<Integer>();
		}
		return this.yacCoeff9;
	}

	/**
	 * Gets the value of the yacCoeff14 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the yacCoeff14 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getYACCoeff14().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getYACCoeff14() {
		if (yacCoeff14 == null) {
			yacCoeff14 = new ArrayList<Integer>();
		}
		return this.yacCoeff14;
	}

	/**
	 * Gets the value of the yacCoeff20 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the yacCoeff20 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getYACCoeff20().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getYACCoeff20() {
		if (yacCoeff20 == null) {
			yacCoeff20 = new ArrayList<Integer>();
		}
		return this.yacCoeff20;
	}

	/**
	 * Gets the value of the yacCoeff27 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the yacCoeff27 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getYACCoeff27().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getYACCoeff27() {
		if (yacCoeff27 == null) {
			yacCoeff27 = new ArrayList<Integer>();
		}
		return this.yacCoeff27;
	}

	/**
	 * Gets the value of the yacCoeff63 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the yacCoeff63 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getYACCoeff63().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getYACCoeff63() {
		if (yacCoeff63 == null) {
			yacCoeff63 = new ArrayList<Integer>();
		}
		return this.yacCoeff63;
	}

	/**
	 * Gets the value of the cbACCoeff2 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cbACCoeff2 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCbACCoeff2().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCbACCoeff2() {
		if (cbACCoeff2 == null) {
			cbACCoeff2 = new ArrayList<Integer>();
		}
		return this.cbACCoeff2;
	}

	/**
	 * Gets the value of the crACCoeff2 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the crACCoeff2 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCrACCoeff2().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCrACCoeff2() {
		if (crACCoeff2 == null) {
			crACCoeff2 = new ArrayList<Integer>();
		}
		return this.crACCoeff2;
	}

	/**
	 * Gets the value of the cbACCoeff5 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cbACCoeff5 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCbACCoeff5().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCbACCoeff5() {
		if (cbACCoeff5 == null) {
			cbACCoeff5 = new ArrayList<Integer>();
		}
		return this.cbACCoeff5;
	}

	/**
	 * Gets the value of the crACCoeff5 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the crACCoeff5 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCrACCoeff5().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCrACCoeff5() {
		if (crACCoeff5 == null) {
			crACCoeff5 = new ArrayList<Integer>();
		}
		return this.crACCoeff5;
	}

	/**
	 * Gets the value of the cbACCoeff9 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cbACCoeff9 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCbACCoeff9().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCbACCoeff9() {
		if (cbACCoeff9 == null) {
			cbACCoeff9 = new ArrayList<Integer>();
		}
		return this.cbACCoeff9;
	}

	/**
	 * Gets the value of the crACCoeff9 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the crACCoeff9 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCrACCoeff9().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCrACCoeff9() {
		if (crACCoeff9 == null) {
			crACCoeff9 = new ArrayList<Integer>();
		}
		return this.crACCoeff9;
	}

	/**
	 * Gets the value of the cbACCoeff14 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cbACCoeff14 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCbACCoeff14().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCbACCoeff14() {
		if (cbACCoeff14 == null) {
			cbACCoeff14 = new ArrayList<Integer>();
		}
		return this.cbACCoeff14;
	}

	/**
	 * Gets the value of the crACCoeff14 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the crACCoeff14 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCrACCoeff14().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCrACCoeff14() {
		if (crACCoeff14 == null) {
			crACCoeff14 = new ArrayList<Integer>();
		}
		return this.crACCoeff14;
	}

	/**
	 * Gets the value of the cbACCoeff20 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cbACCoeff20 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCbACCoeff20().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCbACCoeff20() {
		if (cbACCoeff20 == null) {
			cbACCoeff20 = new ArrayList<Integer>();
		}
		return this.cbACCoeff20;
	}

	/**
	 * Gets the value of the crACCoeff20 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the crACCoeff20 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCrACCoeff20().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCrACCoeff20() {
		if (crACCoeff20 == null) {
			crACCoeff20 = new ArrayList<Integer>();
		}
		return this.crACCoeff20;
	}

	/**
	 * Gets the value of the cbACCoeff27 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cbACCoeff27 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCbACCoeff27().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCbACCoeff27() {
		if (cbACCoeff27 == null) {
			cbACCoeff27 = new ArrayList<Integer>();
		}
		return this.cbACCoeff27;
	}

	/**
	 * Gets the value of the crACCoeff27 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the crACCoeff27 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCrACCoeff27().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCrACCoeff27() {
		if (crACCoeff27 == null) {
			crACCoeff27 = new ArrayList<Integer>();
		}
		return this.crACCoeff27;
	}

	/**
	 * Gets the value of the cbACCoeff63 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cbACCoeff63 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCbACCoeff63().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCbACCoeff63() {
		if (cbACCoeff63 == null) {
			cbACCoeff63 = new ArrayList<Integer>();
		}
		return this.cbACCoeff63;
	}

	/**
	 * Gets the value of the crACCoeff63 property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the crACCoeff63 property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCrACCoeff63().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Integer }
	 * 
	 * 
	 */
	public List<Integer> getCrACCoeff63() {
		if (crACCoeff63 == null) {
			crACCoeff63 = new ArrayList<Integer>();
		}
		return this.crACCoeff63;
	}

}
