//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LineScratchDefectType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="LineScratchDefectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prestospace.org/res/defect_quality}VisualImpairmentType">
 *       &lt;sequence>
 *         &lt;element name="ScratchProperties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="horizontalPosition" type="{urn:mpeg:mpeg7:schema:2004}zeroToOneType" />
 *                 &lt;attribute name="width" type="{urn:mpeg:mpeg7:schema:2004}zeroToOneType" />
 *                 &lt;attribute name="negative" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineScratchDefectType", namespace = "http://www.prestospace.org/res/defect_quality", propOrder = { "scratchProperties" })
public class LineScratchDefectType extends VisualImpairmentType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "ScratchProperties", required = true)
	protected LineScratchDefectType.ScratchProperties scratchProperties;

	/**
	 * Gets the value of the scratchProperties property.
	 * 
	 * @return possible object is
	 *         {@link LineScratchDefectType.ScratchProperties }
	 * 
	 */
	public LineScratchDefectType.ScratchProperties getScratchProperties() {
		return scratchProperties;
	}

	/**
	 * Sets the value of the scratchProperties property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link LineScratchDefectType.ScratchProperties }
	 * 
	 */
	public void setScratchProperties(LineScratchDefectType.ScratchProperties value) {
		this.scratchProperties = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="horizontalPosition" type="{urn:mpeg:mpeg7:schema:2004}zeroToOneType" />
	 *       &lt;attribute name="width" type="{urn:mpeg:mpeg7:schema:2004}zeroToOneType" />
	 *       &lt;attribute name="negative" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class ScratchProperties implements Serializable {

		private final static long serialVersionUID = 1L;
		@XmlAttribute(name = "horizontalPosition")
		protected Float horizontalPosition;
		@XmlAttribute(name = "width")
		protected Float width;
		@XmlAttribute(name = "negative")
		protected Boolean negative;

		/**
		 * Gets the value of the horizontalPosition property.
		 * 
		 * @return possible object is {@link Float }
		 * 
		 */
		public Float getHorizontalPosition() {
			return horizontalPosition;
		}

		/**
		 * Sets the value of the horizontalPosition property.
		 * 
		 * @param value
		 *            allowed object is {@link Float }
		 * 
		 */
		public void setHorizontalPosition(Float value) {
			this.horizontalPosition = value;
		}

		/**
		 * Gets the value of the width property.
		 * 
		 * @return possible object is {@link Float }
		 * 
		 */
		public Float getWidth() {
			return width;
		}

		/**
		 * Sets the value of the width property.
		 * 
		 * @param value
		 *            allowed object is {@link Float }
		 * 
		 */
		public void setWidth(Float value) {
			this.width = value;
		}

		/**
		 * Gets the value of the negative property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public Boolean isNegative() {
			return negative;
		}

		/**
		 * Sets the value of the negative property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setNegative(Boolean value) {
			this.negative = value;
		}

	}

}
