//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.math.BigInteger;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the eu.prestoprime.model.ext.qa package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _TextureBrowsingTypeScale_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "Scale");
	private final static QName _TextureBrowsingTypeDirection_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "Direction");
	private final static QName _PersonNameTypeGivenName_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "GivenName");
	private final static QName _PersonNameTypeSalutation_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "Salutation");
	private final static QName _PersonNameTypeFamilyName_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "FamilyName");
	private final static QName _PersonNameTypeLinkingName_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "LinkingName");
	private final static QName _PersonNameTypeNumeration_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "Numeration");
	private final static QName _PersonNameTypeTitle_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "Title");
	private final static QName _Spatial2DCoordinateSystemTypeLocalCoordinateSystemSrcPixel_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "SrcPixel");
	private final static QName _Spatial2DCoordinateSystemTypeLocalCoordinateSystemCoordPoint_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "CoordPoint");
	private final static QName _Spatial2DCoordinateSystemTypeLocalCoordinateSystemPixel_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "Pixel");
	private final static QName _Spatial2DCoordinateSystemTypeLocalCoordinateSystemCurrPixel_QNAME = new QName("urn:mpeg:mpeg7:schema:2004", "CurrPixel");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: eu.prestoprime.model.ext.qa
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link SpatioTemporalLocatorType }
	 * 
	 */
	public SpatioTemporalLocatorType createSpatioTemporalLocatorType() {
		return new SpatioTemporalLocatorType();
	}

	/**
	 * Create an instance of {@link AudioSignalQualityType }
	 * 
	 */
	public AudioSignalQualityType createAudioSignalQualityType() {
		return new AudioSignalQualityType();
	}

	/**
	 * Create an instance of {@link KeywordAnnotationType }
	 * 
	 */
	public KeywordAnnotationType createKeywordAnnotationType() {
		return new KeywordAnnotationType();
	}

	/**
	 * Create an instance of {@link Spatial2DCoordinateSystemType }
	 * 
	 */
	public Spatial2DCoordinateSystemType createSpatial2DCoordinateSystemType() {
		return new Spatial2DCoordinateSystemType();
	}

	/**
	 * Create an instance of {@link CreationType }
	 * 
	 */
	public CreationType createCreationType() {
		return new CreationType();
	}

	/**
	 * Create an instance of {@link MelodySequenceType }
	 * 
	 */
	public MelodySequenceType createMelodySequenceType() {
		return new MelodySequenceType();
	}

	/**
	 * Create an instance of {@link MelodySequenceType.NoteArray }
	 * 
	 */
	public MelodySequenceType.NoteArray createMelodySequenceTypeNoteArray() {
		return new MelodySequenceType.NoteArray();
	}

	/**
	 * Create an instance of {@link MelodySequenceType.StartingNote }
	 * 
	 */
	public MelodySequenceType.StartingNote createMelodySequenceTypeStartingNote() {
		return new MelodySequenceType.StartingNote();
	}

	/**
	 * Create an instance of
	 * {@link MelodySequenceType.StartingNote.StartingPitch }
	 * 
	 */
	public MelodySequenceType.StartingNote.StartingPitch createMelodySequenceTypeStartingNoteStartingPitch() {
		return new MelodySequenceType.StartingNote.StartingPitch();
	}

	/**
	 * Create an instance of {@link MotionActivityType }
	 * 
	 */
	public MotionActivityType createMotionActivityType() {
		return new MotionActivityType();
	}

	/**
	 * Create an instance of {@link ElectronicAddressType }
	 * 
	 */
	public ElectronicAddressType createElectronicAddressType() {
		return new ElectronicAddressType();
	}

	/**
	 * Create an instance of {@link MediaQualityType }
	 * 
	 */
	public MediaQualityType createMediaQualityType() {
		return new MediaQualityType();
	}

	/**
	 * Create an instance of {@link RatingType }
	 * 
	 */
	public RatingType createRatingType() {
		return new RatingType();
	}

	/**
	 * Create an instance of {@link MediaFormatType }
	 * 
	 */
	public MediaFormatType createMediaFormatType() {
		return new MediaFormatType();
	}

	/**
	 * Create an instance of {@link MediaFormatType.AudioCoding }
	 * 
	 */
	public MediaFormatType.AudioCoding createMediaFormatTypeAudioCoding() {
		return new MediaFormatType.AudioCoding();
	}

	/**
	 * Create an instance of {@link MediaFormatType.VisualCoding }
	 * 
	 */
	public MediaFormatType.VisualCoding createMediaFormatTypeVisualCoding() {
		return new MediaFormatType.VisualCoding();
	}

	/**
	 * Create an instance of {@link PersonGroupType }
	 * 
	 */
	public PersonGroupType createPersonGroupType() {
		return new PersonGroupType();
	}

	/**
	 * Create an instance of {@link NonMixtureAmountOfMotionType }
	 * 
	 */
	public NonMixtureAmountOfMotionType createNonMixtureAmountOfMotionType() {
		return new NonMixtureAmountOfMotionType();
	}

	/**
	 * Create an instance of {@link OrganizationType }
	 * 
	 */
	public OrganizationType createOrganizationType() {
		return new OrganizationType();
	}

	/**
	 * Create an instance of {@link SpeakerInfoType }
	 * 
	 */
	public SpeakerInfoType createSpeakerInfoType() {
		return new SpeakerInfoType();
	}

	/**
	 * Create an instance of {@link SpeakerInfoType.PhoneIndex }
	 * 
	 */
	public SpeakerInfoType.PhoneIndex createSpeakerInfoTypePhoneIndex() {
		return new SpeakerInfoType.PhoneIndex();
	}

	/**
	 * Create an instance of {@link SpeakerInfoType.WordIndex }
	 * 
	 */
	public SpeakerInfoType.WordIndex createSpeakerInfoTypeWordIndex() {
		return new SpeakerInfoType.WordIndex();
	}

	/**
	 * Create an instance of {@link WordLexiconType }
	 * 
	 */
	public WordLexiconType createWordLexiconType() {
		return new WordLexiconType();
	}

	/**
	 * Create an instance of {@link CreationToolType }
	 * 
	 */
	public CreationToolType createCreationToolType() {
		return new CreationToolType();
	}

	/**
	 * Create an instance of {@link MotionTrajectoryType }
	 * 
	 */
	public MotionTrajectoryType createMotionTrajectoryType() {
		return new MotionTrajectoryType();
	}

	/**
	 * Create an instance of {@link MotionTrajectoryType.CoordDef }
	 * 
	 */
	public MotionTrajectoryType.CoordDef createMotionTrajectoryTypeCoordDef() {
		return new MotionTrajectoryType.CoordDef();
	}

	/**
	 * Create an instance of {@link PersonType }
	 * 
	 */
	public PersonType createPersonType() {
		return new PersonType();
	}

	/**
	 * Create an instance of {@link KeyType }
	 * 
	 */
	public KeyType createKeyType() {
		return new KeyType();
	}

	/**
	 * Create an instance of {@link ClassificationType }
	 * 
	 */
	public ClassificationType createClassificationType() {
		return new ClassificationType();
	}

	/**
	 * Create an instance of {@link TemporalInterpolationType }
	 * 
	 */
	public TemporalInterpolationType createTemporalInterpolationType() {
		return new TemporalInterpolationType();
	}

	/**
	 * Create an instance of
	 * {@link TemporalInterpolationType.InterpolationFunctions }
	 * 
	 */
	public TemporalInterpolationType.InterpolationFunctions createTemporalInterpolationTypeInterpolationFunctions() {
		return new TemporalInterpolationType.InterpolationFunctions();
	}

	/**
	 * Create an instance of {@link AvailabilityType }
	 * 
	 */
	public AvailabilityType createAvailabilityType() {
		return new AvailabilityType();
	}

	/**
	 * Create an instance of {@link DominantColorType }
	 * 
	 */
	public DominantColorType createDominantColorType() {
		return new DominantColorType();
	}

	/**
	 * Create an instance of {@link ParametricMotionType }
	 * 
	 */
	public ParametricMotionType createParametricMotionType() {
		return new ParametricMotionType();
	}

	/**
	 * Create an instance of {@link ColorSamplingType }
	 * 
	 */
	public ColorSamplingType createColorSamplingType() {
		return new ColorSamplingType();
	}

	/**
	 * Create an instance of {@link ColorSamplingType.Field }
	 * 
	 */
	public ColorSamplingType.Field createColorSamplingTypeField() {
		return new ColorSamplingType.Field();
	}

	/**
	 * Create an instance of {@link ColorSamplingType.Field.Component }
	 * 
	 */
	public ColorSamplingType.Field.Component createColorSamplingTypeFieldComponent() {
		return new ColorSamplingType.Field.Component();
	}

	/**
	 * Create an instance of {@link SpokenContentLatticeType }
	 * 
	 */
	public SpokenContentLatticeType createSpokenContentLatticeType() {
		return new SpokenContentLatticeType();
	}

	/**
	 * Create an instance of {@link SpokenContentLatticeType.Block }
	 * 
	 */
	public SpokenContentLatticeType.Block createSpokenContentLatticeTypeBlock() {
		return new SpokenContentLatticeType.Block();
	}

	/**
	 * Create an instance of {@link SpokenContentLatticeType.Block.Node }
	 * 
	 */
	public SpokenContentLatticeType.Block.Node createSpokenContentLatticeTypeBlockNode() {
		return new SpokenContentLatticeType.Block.Node();
	}

	/**
	 * Create an instance of {@link RegionLocatorType }
	 * 
	 */
	public RegionLocatorType createRegionLocatorType() {
		return new RegionLocatorType();
	}

	/**
	 * Create an instance of {@link PlaceType }
	 * 
	 */
	public PlaceType createPlaceType() {
		return new PlaceType();
	}

	/**
	 * Create an instance of {@link ContourShapeType }
	 * 
	 */
	public ContourShapeType createContourShapeType() {
		return new ContourShapeType();
	}

	/**
	 * Create an instance of {@link VisualImpairmentType }
	 * 
	 */
	public VisualImpairmentType createVisualImpairmentType() {
		return new VisualImpairmentType();
	}

	/**
	 * Create an instance of {@link DropoutLevelType }
	 * 
	 */
	public DropoutLevelType createDropoutLevelType() {
		return new DropoutLevelType();
	}

	/**
	 * Create an instance of {@link DropoutDefectType }
	 * 
	 */
	public DropoutDefectType createDropoutDefectType() {
		return new DropoutDefectType();
	}

	/**
	 * Create an instance of {@link DropoutDefectType.AffectedArea }
	 * 
	 */
	public DropoutDefectType.AffectedArea createDropoutDefectTypeAffectedArea() {
		return new DropoutDefectType.AffectedArea();
	}

	/**
	 * Create an instance of {@link WowFlutterDefectType }
	 * 
	 */
	public WowFlutterDefectType createWowFlutterDefectType() {
		return new WowFlutterDefectType();
	}

	/**
	 * Create an instance of {@link FlickerLevelType }
	 * 
	 */
	public FlickerLevelType createFlickerLevelType() {
		return new FlickerLevelType();
	}

	/**
	 * Create an instance of {@link FlickerLevelType.FrequencyDistribution }
	 * 
	 */
	public FlickerLevelType.FrequencyDistribution createFlickerLevelTypeFrequencyDistribution() {
		return new FlickerLevelType.FrequencyDistribution();
	}

	/**
	 * Create an instance of {@link ColorRangeDefectType }
	 * 
	 */
	public ColorRangeDefectType createColorRangeDefectType() {
		return new ColorRangeDefectType();
	}

	/**
	 * Create an instance of {@link ColorRangeDefectType.Channel }
	 * 
	 */
	public ColorRangeDefectType.Channel createColorRangeDefectTypeChannel() {
		return new ColorRangeDefectType.Channel();
	}

	/**
	 * Create an instance of {@link LineScratchDefectType }
	 * 
	 */
	public LineScratchDefectType createLineScratchDefectType() {
		return new LineScratchDefectType();
	}

	/**
	 * Create an instance of {@link BlurLevelType }
	 * 
	 */
	public BlurLevelType createBlurLevelType() {
		return new BlurLevelType();
	}

	/**
	 * Create an instance of {@link ChannelMisalignmentType }
	 * 
	 */
	public ChannelMisalignmentType createChannelMisalignmentType() {
		return new ChannelMisalignmentType();
	}

	/**
	 * Create an instance of {@link NoiseGrainLevelType }
	 * 
	 */
	public NoiseGrainLevelType createNoiseGrainLevelType() {
		return new NoiseGrainLevelType();
	}

	/**
	 * Create an instance of {@link NoiseGrainLevelType.BrightnessDependency }
	 * 
	 */
	public NoiseGrainLevelType.BrightnessDependency createNoiseGrainLevelTypeBrightnessDependency() {
		return new NoiseGrainLevelType.BrightnessDependency();
	}

	/**
	 * Create an instance of {@link ImageInstabilityType }
	 * 
	 */
	public ImageInstabilityType createImageInstabilityType() {
		return new ImageInstabilityType();
	}

	/**
	 * Create an instance of {@link DustLevelType }
	 * 
	 */
	public DustLevelType createDustLevelType() {
		return new DustLevelType();
	}

	/**
	 * Create an instance of {@link UpconversionType }
	 * 
	 */
	public UpconversionType createUpconversionType() {
		return new UpconversionType();
	}

	/**
	 * Create an instance of {@link BlockingLevelType }
	 * 
	 */
	public BlockingLevelType createBlockingLevelType() {
		return new BlockingLevelType();
	}

	/**
	 * Create an instance of {@link ChannelListType }
	 * 
	 */
	public ChannelListType createChannelListType() {
		return new ChannelListType();
	}

	/**
	 * Create an instance of {@link BlackFrameDefectType }
	 * 
	 */
	public BlackFrameDefectType createBlackFrameDefectType() {
		return new BlackFrameDefectType();
	}

	/**
	 * Create an instance of {@link VideoBreakupDefectType }
	 * 
	 */
	public VideoBreakupDefectType createVideoBreakupDefectType() {
		return new VideoBreakupDefectType();
	}

	/**
	 * Create an instance of {@link FullFrameDamageType }
	 * 
	 */
	public FullFrameDamageType createFullFrameDamageType() {
		return new FullFrameDamageType();
	}

	/**
	 * Create an instance of {@link VisualSignalQualityType }
	 * 
	 */
	public VisualSignalQualityType createVisualSignalQualityType() {
		return new VisualSignalQualityType();
	}

	/**
	 * Create an instance of {@link LineScratchLevelType }
	 * 
	 */
	public LineScratchLevelType createLineScratchLevelType() {
		return new LineScratchLevelType();
	}

	/**
	 * Create an instance of {@link FrameLossType }
	 * 
	 */
	public FrameLossType createFrameLossType() {
		return new FrameLossType();
	}

	/**
	 * Create an instance of {@link PitchShiftDefectType }
	 * 
	 */
	public PitchShiftDefectType createPitchShiftDefectType() {
		return new PitchShiftDefectType();
	}

	/**
	 * Create an instance of {@link ImpairmentSampleListType }
	 * 
	 */
	public ImpairmentSampleListType createImpairmentSampleListType() {
		return new ImpairmentSampleListType();
	}

	/**
	 * Create an instance of {@link Mpeg7 }
	 * 
	 */
	public Mpeg7 createMpeg7() {
		return new Mpeg7();
	}

	/**
	 * Create an instance of {@link DescriptionProfileType }
	 * 
	 */
	public DescriptionProfileType createDescriptionProfileType() {
		return new DescriptionProfileType();
	}

	/**
	 * Create an instance of {@link DescriptionMetadataType }
	 * 
	 */
	public DescriptionMetadataType createDescriptionMetadataType() {
		return new DescriptionMetadataType();
	}

	/**
	 * Create an instance of {@link MediaAgentType }
	 * 
	 */
	public MediaAgentType createMediaAgentType() {
		return new MediaAgentType();
	}

	/**
	 * Create an instance of {@link SilenceType }
	 * 
	 */
	public SilenceType createSilenceType() {
		return new SilenceType();
	}

	/**
	 * Create an instance of {@link AudioSpectrumBasisType }
	 * 
	 */
	public AudioSpectrumBasisType createAudioSpectrumBasisType() {
		return new AudioSpectrumBasisType();
	}

	/**
	 * Create an instance of {@link AudioVisualSegmentType }
	 * 
	 */
	public AudioVisualSegmentType createAudioVisualSegmentType() {
		return new AudioVisualSegmentType();
	}

	/**
	 * Create an instance of {@link MixtureCameraMotionSegmentType }
	 * 
	 */
	public MixtureCameraMotionSegmentType createMixtureCameraMotionSegmentType() {
		return new MixtureCameraMotionSegmentType();
	}

	/**
	 * Create an instance of
	 * {@link AudioVisualSegmentMediaSourceDecompositionType }
	 * 
	 */
	public AudioVisualSegmentMediaSourceDecompositionType createAudioVisualSegmentMediaSourceDecompositionType() {
		return new AudioVisualSegmentMediaSourceDecompositionType();
	}

	/**
	 * Create an instance of {@link CreationInformationType }
	 * 
	 */
	public CreationInformationType createCreationInformationType() {
		return new CreationInformationType();
	}

	/**
	 * Create an instance of {@link IntegerMatrixType }
	 * 
	 */
	public IntegerMatrixType createIntegerMatrixType() {
		return new IntegerMatrixType();
	}

	/**
	 * Create an instance of {@link DoubleMatrixType }
	 * 
	 */
	public DoubleMatrixType createDoubleMatrixType() {
		return new DoubleMatrixType();
	}

	/**
	 * Create an instance of {@link AudioSpectrumProjectionType }
	 * 
	 */
	public AudioSpectrumProjectionType createAudioSpectrumProjectionType() {
		return new AudioSpectrumProjectionType();
	}

	/**
	 * Create an instance of {@link SummarySegmentType }
	 * 
	 */
	public SummarySegmentType createSummarySegmentType() {
		return new SummarySegmentType();
	}

	/**
	 * Create an instance of {@link StillRegionSpatialDecompositionType }
	 * 
	 */
	public StillRegionSpatialDecompositionType createStillRegionSpatialDecompositionType() {
		return new StillRegionSpatialDecompositionType();
	}

	/**
	 * Create an instance of {@link InstrumentTimbreType }
	 * 
	 */
	public InstrumentTimbreType createInstrumentTimbreType() {
		return new InstrumentTimbreType();
	}

	/**
	 * Create an instance of {@link AudioTempoType }
	 * 
	 */
	public AudioTempoType createAudioTempoType() {
		return new AudioTempoType();
	}

	/**
	 * Create an instance of {@link CreatorType }
	 * 
	 */
	public CreatorType createCreatorType() {
		return new CreatorType();
	}

	/**
	 * Create an instance of {@link FocusOfExpansionType }
	 * 
	 */
	public FocusOfExpansionType createFocusOfExpansionType() {
		return new FocusOfExpansionType();
	}

	/**
	 * Create an instance of {@link StructuredAnnotationType }
	 * 
	 */
	public StructuredAnnotationType createStructuredAnnotationType() {
		return new StructuredAnnotationType();
	}

	/**
	 * Create an instance of {@link HarmonicSpectralCentroidType }
	 * 
	 */
	public HarmonicSpectralCentroidType createHarmonicSpectralCentroidType() {
		return new HarmonicSpectralCentroidType();
	}

	/**
	 * Create an instance of {@link MediaProfileType }
	 * 
	 */
	public MediaProfileType createMediaProfileType() {
		return new MediaProfileType();
	}

	/**
	 * Create an instance of {@link MediaRelIncrTimePointType }
	 * 
	 */
	public MediaRelIncrTimePointType createMediaRelIncrTimePointType() {
		return new MediaRelIncrTimePointType();
	}

	/**
	 * Create an instance of {@link AudioBPMType }
	 * 
	 */
	public AudioBPMType createAudioBPMType() {
		return new AudioBPMType();
	}

	/**
	 * Create an instance of {@link TextAnnotationType }
	 * 
	 */
	public TextAnnotationType createTextAnnotationType() {
		return new TextAnnotationType();
	}

	/**
	 * Create an instance of {@link ShapeVariationType }
	 * 
	 */
	public ShapeVariationType createShapeVariationType() {
		return new ShapeVariationType();
	}

	/**
	 * Create an instance of {@link SummaryDescriptionType }
	 * 
	 */
	public SummaryDescriptionType createSummaryDescriptionType() {
		return new SummaryDescriptionType();
	}

	/**
	 * Create an instance of {@link ControlledTermUseType }
	 * 
	 */
	public ControlledTermUseType createControlledTermUseType() {
		return new ControlledTermUseType();
	}

	/**
	 * Create an instance of {@link ContentEntityType }
	 * 
	 */
	public ContentEntityType createContentEntityType() {
		return new ContentEntityType();
	}

	/**
	 * Create an instance of {@link FractionalPresenceType }
	 * 
	 */
	public FractionalPresenceType createFractionalPresenceType() {
		return new FractionalPresenceType();
	}

	/**
	 * Create an instance of {@link MovingRegionSpatioTemporalDecompositionType }
	 * 
	 */
	public MovingRegionSpatioTemporalDecompositionType createMovingRegionSpatioTemporalDecompositionType() {
		return new MovingRegionSpatioTemporalDecompositionType();
	}

	/**
	 * Create an instance of {@link MeterType }
	 * 
	 */
	public MeterType createMeterType() {
		return new MeterType();
	}

	/**
	 * Create an instance of {@link TemporalSegmentLocatorType }
	 * 
	 */
	public TemporalSegmentLocatorType createTemporalSegmentLocatorType() {
		return new TemporalSegmentLocatorType();
	}

	/**
	 * Create an instance of {@link SummarizationType }
	 * 
	 */
	public SummarizationType createSummarizationType() {
		return new SummarizationType();
	}

	/**
	 * Create an instance of {@link ParameterTrajectoryType }
	 * 
	 */
	public ParameterTrajectoryType createParameterTrajectoryType() {
		return new ParameterTrajectoryType();
	}

	/**
	 * Create an instance of {@link HarmonicSpectralVariationType }
	 * 
	 */
	public HarmonicSpectralVariationType createHarmonicSpectralVariationType() {
		return new HarmonicSpectralVariationType();
	}

	/**
	 * Create an instance of {@link StillRegionType }
	 * 
	 */
	public StillRegionType createStillRegionType() {
		return new StillRegionType();
	}

	/**
	 * Create an instance of {@link MediaInformationType }
	 * 
	 */
	public MediaInformationType createMediaInformationType() {
		return new MediaInformationType();
	}

	/**
	 * Create an instance of {@link MelodyContourType }
	 * 
	 */
	public MelodyContourType createMelodyContourType() {
		return new MelodyContourType();
	}

	/**
	 * Create an instance of {@link VisualSummaryComponentType }
	 * 
	 */
	public VisualSummaryComponentType createVisualSummaryComponentType() {
		return new VisualSummaryComponentType();
	}

	/**
	 * Create an instance of {@link AudioVisualSegmentTemporalDecompositionType }
	 * 
	 */
	public AudioVisualSegmentTemporalDecompositionType createAudioVisualSegmentTemporalDecompositionType() {
		return new AudioVisualSegmentTemporalDecompositionType();
	}

	/**
	 * Create an instance of {@link TermUseType }
	 * 
	 */
	public TermUseType createTermUseType() {
		return new TermUseType();
	}

	/**
	 * Create an instance of {@link NameComponentType }
	 * 
	 */
	public NameComponentType createNameComponentType() {
		return new NameComponentType();
	}

	/**
	 * Create an instance of {@link MovingRegionType }
	 * 
	 */
	public MovingRegionType createMovingRegionType() {
		return new MovingRegionType();
	}

	/**
	 * Create an instance of {@link TitleType }
	 * 
	 */
	public TitleType createTitleType() {
		return new TitleType();
	}

	/**
	 * Create an instance of {@link IrregularVisualTimeSeriesType }
	 * 
	 */
	public IrregularVisualTimeSeriesType createIrregularVisualTimeSeriesType() {
		return new IrregularVisualTimeSeriesType();
	}

	/**
	 * Create an instance of {@link UsageInformationType }
	 * 
	 */
	public UsageInformationType createUsageInformationType() {
		return new UsageInformationType();
	}

	/**
	 * Create an instance of {@link ScalableColorType }
	 * 
	 */
	public ScalableColorType createScalableColorType() {
		return new ScalableColorType();
	}

	/**
	 * Create an instance of {@link SeriesOfVectorType }
	 * 
	 */
	public SeriesOfVectorType createSeriesOfVectorType() {
		return new SeriesOfVectorType();
	}

	/**
	 * Create an instance of {@link SpokenContentIndexEntryType }
	 * 
	 */
	public SpokenContentIndexEntryType createSpokenContentIndexEntryType() {
		return new SpokenContentIndexEntryType();
	}

	/**
	 * Create an instance of {@link SummarySegmentGroupType }
	 * 
	 */
	public SummarySegmentGroupType createSummarySegmentGroupType() {
		return new SummarySegmentGroupType();
	}

	/**
	 * Create an instance of {@link AudioWaveformType }
	 * 
	 */
	public AudioWaveformType createAudioWaveformType() {
		return new AudioWaveformType();
	}

	/**
	 * Create an instance of {@link RightsType }
	 * 
	 */
	public RightsType createRightsType() {
		return new RightsType();
	}

	/**
	 * Create an instance of {@link MediaIncrDurationType }
	 * 
	 */
	public MediaIncrDurationType createMediaIncrDurationType() {
		return new MediaIncrDurationType();
	}

	/**
	 * Create an instance of {@link HarmonicSpectralSpreadType }
	 * 
	 */
	public HarmonicSpectralSpreadType createHarmonicSpectralSpreadType() {
		return new HarmonicSpectralSpreadType();
	}

	/**
	 * Create an instance of {@link RegularVisualTimeSeriesType }
	 * 
	 */
	public RegularVisualTimeSeriesType createRegularVisualTimeSeriesType() {
		return new RegularVisualTimeSeriesType();
	}

	/**
	 * Create an instance of {@link AudioSpectrumFlatnessType }
	 * 
	 */
	public AudioSpectrumFlatnessType createAudioSpectrumFlatnessType() {
		return new AudioSpectrumFlatnessType();
	}

	/**
	 * Create an instance of {@link ImageTextType }
	 * 
	 */
	public ImageTextType createImageTextType() {
		return new ImageTextType();
	}

	/**
	 * Create an instance of {@link HarmonicSpectralDeviationType }
	 * 
	 */
	public HarmonicSpectralDeviationType createHarmonicSpectralDeviationType() {
		return new HarmonicSpectralDeviationType();
	}

	/**
	 * Create an instance of {@link GeographicPointType }
	 * 
	 */
	public GeographicPointType createGeographicPointType() {
		return new GeographicPointType();
	}

	/**
	 * Create an instance of {@link ErrorEventType }
	 * 
	 */
	public ErrorEventType createErrorEventType() {
		return new ErrorEventType();
	}

	/**
	 * Create an instance of {@link HomogeneousTextureType }
	 * 
	 */
	public HomogeneousTextureType createHomogeneousTextureType() {
		return new HomogeneousTextureType();
	}

	/**
	 * Create an instance of {@link PercussiveInstrumentTimbreType }
	 * 
	 */
	public PercussiveInstrumentTimbreType createPercussiveInstrumentTimbreType() {
		return new PercussiveInstrumentTimbreType();
	}

	/**
	 * Create an instance of {@link AudioSpectrumSpreadType }
	 * 
	 */
	public AudioSpectrumSpreadType createAudioSpectrumSpreadType() {
		return new AudioSpectrumSpreadType();
	}

	/**
	 * Create an instance of {@link AudioSummaryComponentType }
	 * 
	 */
	public AudioSummaryComponentType createAudioSummaryComponentType() {
		return new AudioSummaryComponentType();
	}

	/**
	 * Create an instance of {@link ExtendedLanguageType }
	 * 
	 */
	public ExtendedLanguageType createExtendedLanguageType() {
		return new ExtendedLanguageType();
	}

	/**
	 * Create an instance of {@link SpokenContentLinkType }
	 * 
	 */
	public SpokenContentLinkType createSpokenContentLinkType() {
		return new SpokenContentLinkType();
	}

	/**
	 * Create an instance of {@link EdgeHistogramType }
	 * 
	 */
	public EdgeHistogramType createEdgeHistogramType() {
		return new EdgeHistogramType();
	}

	/**
	 * Create an instance of {@link AudioSpectrumCentroidType }
	 * 
	 */
	public AudioSpectrumCentroidType createAudioSpectrumCentroidType() {
		return new AudioSpectrumCentroidType();
	}

	/**
	 * Create an instance of {@link VideoSegmentType }
	 * 
	 */
	public VideoSegmentType createVideoSegmentType() {
		return new VideoSegmentType();
	}

	/**
	 * Create an instance of {@link MixtureAmountOfMotionType }
	 * 
	 */
	public MixtureAmountOfMotionType createMixtureAmountOfMotionType() {
		return new MixtureAmountOfMotionType();
	}

	/**
	 * Create an instance of {@link RelatedMaterialType }
	 * 
	 */
	public RelatedMaterialType createRelatedMaterialType() {
		return new RelatedMaterialType();
	}

	/**
	 * Create an instance of {@link TextualType }
	 * 
	 */
	public TextualType createTextualType() {
		return new TextualType();
	}

	/**
	 * Create an instance of {@link TemporalCentroidType }
	 * 
	 */
	public TemporalCentroidType createTemporalCentroidType() {
		return new TemporalCentroidType();
	}

	/**
	 * Create an instance of {@link AudioSegmentTemporalDecompositionType }
	 * 
	 */
	public AudioSegmentTemporalDecompositionType createAudioSegmentTemporalDecompositionType() {
		return new AudioSegmentTemporalDecompositionType();
	}

	/**
	 * Create an instance of {@link AudioVisualType }
	 * 
	 */
	public AudioVisualType createAudioVisualType() {
		return new AudioVisualType();
	}

	/**
	 * Create an instance of {@link VideoTextType }
	 * 
	 */
	public VideoTextType createVideoTextType() {
		return new VideoTextType();
	}

	/**
	 * Create an instance of {@link AudioSegmentType }
	 * 
	 */
	public AudioSegmentType createAudioSegmentType() {
		return new AudioSegmentType();
	}

	/**
	 * Create an instance of {@link NonMixtureCameraMotionSegmentType }
	 * 
	 */
	public NonMixtureCameraMotionSegmentType createNonMixtureCameraMotionSegmentType() {
		return new NonMixtureCameraMotionSegmentType();
	}

	/**
	 * Create an instance of {@link FigureTrajectoryType }
	 * 
	 */
	public FigureTrajectoryType createFigureTrajectoryType() {
		return new FigureTrajectoryType();
	}

	/**
	 * Create an instance of {@link LogAttackTimeType }
	 * 
	 */
	public LogAttackTimeType createLogAttackTimeType() {
		return new LogAttackTimeType();
	}

	/**
	 * Create an instance of {@link ColorLayoutType }
	 * 
	 */
	public ColorLayoutType createColorLayoutType() {
		return new ColorLayoutType();
	}

	/**
	 * Create an instance of {@link RelativeDelayType }
	 * 
	 */
	public RelativeDelayType createRelativeDelayType() {
		return new RelativeDelayType();
	}

	/**
	 * Create an instance of {@link MinusOneToOneMatrixType }
	 * 
	 */
	public MinusOneToOneMatrixType createMinusOneToOneMatrixType() {
		return new MinusOneToOneMatrixType();
	}

	/**
	 * Create an instance of {@link CameraMotionType }
	 * 
	 */
	public CameraMotionType createCameraMotionType() {
		return new CameraMotionType();
	}

	/**
	 * Create an instance of {@link AudioPowerType }
	 * 
	 */
	public AudioPowerType createAudioPowerType() {
		return new AudioPowerType();
	}

	/**
	 * Create an instance of {@link TransmissionTechnologyType }
	 * 
	 */
	public TransmissionTechnologyType createTransmissionTechnologyType() {
		return new TransmissionTechnologyType();
	}

	/**
	 * Create an instance of {@link MediaInstanceType }
	 * 
	 */
	public MediaInstanceType createMediaInstanceType() {
		return new MediaInstanceType();
	}

	/**
	 * Create an instance of {@link MediaLocatorType }
	 * 
	 */
	public MediaLocatorType createMediaLocatorType() {
		return new MediaLocatorType();
	}

	/**
	 * Create an instance of {@link TitleMediaType }
	 * 
	 */
	public TitleMediaType createTitleMediaType() {
		return new TitleMediaType();
	}

	/**
	 * Create an instance of {@link MovingRegionFeatureType }
	 * 
	 */
	public MovingRegionFeatureType createMovingRegionFeatureType() {
		return new MovingRegionFeatureType();
	}

	/**
	 * Create an instance of {@link GofGopFeatureType }
	 * 
	 */
	public GofGopFeatureType createGofGopFeatureType() {
		return new GofGopFeatureType();
	}

	/**
	 * Create an instance of {@link MelodyType }
	 * 
	 */
	public MelodyType createMelodyType() {
		return new MelodyType();
	}

	/**
	 * Create an instance of {@link TextureBrowsingType }
	 * 
	 */
	public TextureBrowsingType createTextureBrowsingType() {
		return new TextureBrowsingType();
	}

	/**
	 * Create an instance of {@link SeriesOfScalarBinaryType }
	 * 
	 */
	public SeriesOfScalarBinaryType createSeriesOfScalarBinaryType() {
		return new SeriesOfScalarBinaryType();
	}

	/**
	 * Create an instance of {@link PhoneLexiconType }
	 * 
	 */
	public PhoneLexiconType createPhoneLexiconType() {
		return new PhoneLexiconType();
	}

	/**
	 * Create an instance of {@link SeriesOfScalarType }
	 * 
	 */
	public SeriesOfScalarType createSeriesOfScalarType() {
		return new SeriesOfScalarType();
	}

	/**
	 * Create an instance of {@link BandwidthType }
	 * 
	 */
	public BandwidthType createBandwidthType() {
		return new BandwidthType();
	}

	/**
	 * Create an instance of {@link SilenceHeaderType }
	 * 
	 */
	public SilenceHeaderType createSilenceHeaderType() {
		return new SilenceHeaderType();
	}

	/**
	 * Create an instance of {@link BackgroundNoiseLevelType }
	 * 
	 */
	public BackgroundNoiseLevelType createBackgroundNoiseLevelType() {
		return new BackgroundNoiseLevelType();
	}

	/**
	 * Create an instance of {@link ColorSpaceType }
	 * 
	 */
	public ColorSpaceType createColorSpaceType() {
		return new ColorSpaceType();
	}

	/**
	 * Create an instance of {@link VideoSegmentFeatureType }
	 * 
	 */
	public VideoSegmentFeatureType createVideoSegmentFeatureType() {
		return new VideoSegmentFeatureType();
	}

	/**
	 * Create an instance of {@link GoFGoPColorType }
	 * 
	 */
	public GoFGoPColorType createGoFGoPColorType() {
		return new GoFGoPColorType();
	}

	/**
	 * Create an instance of {@link ConfusionCountType }
	 * 
	 */
	public ConfusionCountType createConfusionCountType() {
		return new ConfusionCountType();
	}

	/**
	 * Create an instance of {@link FaceRecognitionType }
	 * 
	 */
	public FaceRecognitionType createFaceRecognitionType() {
		return new FaceRecognitionType();
	}

	/**
	 * Create an instance of {@link AudioFundamentalFrequencyType }
	 * 
	 */
	public AudioFundamentalFrequencyType createAudioFundamentalFrequencyType() {
		return new AudioFundamentalFrequencyType();
	}

	/**
	 * Create an instance of {@link BalanceType }
	 * 
	 */
	public BalanceType createBalanceType() {
		return new BalanceType();
	}

	/**
	 * Create an instance of {@link AudioSignatureType }
	 * 
	 */
	public AudioSignatureType createAudioSignatureType() {
		return new AudioSignatureType();
	}

	/**
	 * Create an instance of {@link RelationType }
	 * 
	 */
	public RelationType createRelationType() {
		return new RelationType();
	}

	/**
	 * Create an instance of {@link ColorTemperatureType }
	 * 
	 */
	public ColorTemperatureType createColorTemperatureType() {
		return new ColorTemperatureType();
	}

	/**
	 * Create an instance of {@link FloatDiagonalMatrixType }
	 * 
	 */
	public FloatDiagonalMatrixType createFloatDiagonalMatrixType() {
		return new FloatDiagonalMatrixType();
	}

	/**
	 * Create an instance of {@link UniqueIDType }
	 * 
	 */
	public UniqueIDType createUniqueIDType() {
		return new UniqueIDType();
	}

	/**
	 * Create an instance of {@link VideoSegmentTemporalDecompositionType }
	 * 
	 */
	public VideoSegmentTemporalDecompositionType createVideoSegmentTemporalDecompositionType() {
		return new VideoSegmentTemporalDecompositionType();
	}

	/**
	 * Create an instance of {@link ProbabilityMatrixType }
	 * 
	 */
	public ProbabilityMatrixType createProbabilityMatrixType() {
		return new ProbabilityMatrixType();
	}

	/**
	 * Create an instance of {@link AudioHarmonicityType }
	 * 
	 */
	public AudioHarmonicityType createAudioHarmonicityType() {
		return new AudioHarmonicityType();
	}

	/**
	 * Create an instance of {@link SeriesOfVectorBinaryType }
	 * 
	 */
	public SeriesOfVectorBinaryType createSeriesOfVectorBinaryType() {
		return new SeriesOfVectorBinaryType();
	}

	/**
	 * Create an instance of {@link VideoSegmentSpatioTemporalDecompositionType }
	 * 
	 */
	public VideoSegmentSpatioTemporalDecompositionType createVideoSegmentSpatioTemporalDecompositionType() {
		return new VideoSegmentSpatioTemporalDecompositionType();
	}

	/**
	 * Create an instance of {@link IlluminationInvariantColorType }
	 * 
	 */
	public IlluminationInvariantColorType createIlluminationInvariantColorType() {
		return new IlluminationInvariantColorType();
	}

	/**
	 * Create an instance of {@link SequentialSummaryType }
	 * 
	 */
	public SequentialSummaryType createSequentialSummaryType() {
		return new SequentialSummaryType();
	}

	/**
	 * Create an instance of {@link PersonNameType }
	 * 
	 */
	public PersonNameType createPersonNameType() {
		return new PersonNameType();
	}

	/**
	 * Create an instance of {@link ColorStructureType }
	 * 
	 */
	public ColorStructureType createColorStructureType() {
		return new ColorStructureType();
	}

	/**
	 * Create an instance of {@link Shape3DType }
	 * 
	 */
	public Shape3DType createShape3DType() {
		return new Shape3DType();
	}

	/**
	 * Create an instance of {@link BoxListType }
	 * 
	 */
	public BoxListType createBoxListType() {
		return new BoxListType();
	}

	/**
	 * Create an instance of {@link ReferenceType }
	 * 
	 */
	public ReferenceType createReferenceType() {
		return new ReferenceType();
	}

	/**
	 * Create an instance of {@link DisseminationType }
	 * 
	 */
	public DisseminationType createDisseminationType() {
		return new DisseminationType();
	}

	/**
	 * Create an instance of {@link HierarchicalSummaryType }
	 * 
	 */
	public HierarchicalSummaryType createHierarchicalSummaryType() {
		return new HierarchicalSummaryType();
	}

	/**
	 * Create an instance of {@link CrossChannelCorrelationType }
	 * 
	 */
	public CrossChannelCorrelationType createCrossChannelCorrelationType() {
		return new CrossChannelCorrelationType();
	}

	/**
	 * Create an instance of {@link HarmonicInstrumentTimbreType }
	 * 
	 */
	public HarmonicInstrumentTimbreType createHarmonicInstrumentTimbreType() {
		return new HarmonicInstrumentTimbreType();
	}

	/**
	 * Create an instance of {@link SpokenContentHeaderType }
	 * 
	 */
	public SpokenContentHeaderType createSpokenContentHeaderType() {
		return new SpokenContentHeaderType();
	}

	/**
	 * Create an instance of {@link DcOffsetType }
	 * 
	 */
	public DcOffsetType createDcOffsetType() {
		return new DcOffsetType();
	}

	/**
	 * Create an instance of {@link GridLayoutType }
	 * 
	 */
	public GridLayoutType createGridLayoutType() {
		return new GridLayoutType();
	}

	/**
	 * Create an instance of {@link AudioSpectrumEnvelopeType }
	 * 
	 */
	public AudioSpectrumEnvelopeType createAudioSpectrumEnvelopeType() {
		return new AudioSpectrumEnvelopeType();
	}

	/**
	 * Create an instance of {@link MediaIdentificationType }
	 * 
	 */
	public MediaIdentificationType createMediaIdentificationType() {
		return new MediaIdentificationType();
	}

	/**
	 * Create an instance of {@link StillRegionFeatureType }
	 * 
	 */
	public StillRegionFeatureType createStillRegionFeatureType() {
		return new StillRegionFeatureType();
	}

	/**
	 * Create an instance of {@link ColorQuantizationType }
	 * 
	 */
	public ColorQuantizationType createColorQuantizationType() {
		return new ColorQuantizationType();
	}

	/**
	 * Create an instance of {@link AdvancedFaceRecognitionType }
	 * 
	 */
	public AdvancedFaceRecognitionType createAdvancedFaceRecognitionType() {
		return new AdvancedFaceRecognitionType();
	}

	/**
	 * Create an instance of {@link RegionShapeType }
	 * 
	 */
	public RegionShapeType createRegionShapeType() {
		return new RegionShapeType();
	}

	/**
	 * Create an instance of {@link MediaTimeType }
	 * 
	 */
	public MediaTimeType createMediaTimeType() {
		return new MediaTimeType();
	}

	/**
	 * Create an instance of {@link DoubleDiagonalMatrixType }
	 * 
	 */
	public DoubleDiagonalMatrixType createDoubleDiagonalMatrixType() {
		return new DoubleDiagonalMatrixType();
	}

	/**
	 * Create an instance of {@link TimeType }
	 * 
	 */
	public TimeType createTimeType() {
		return new TimeType();
	}

	/**
	 * Create an instance of {@link ImageLocatorType }
	 * 
	 */
	public ImageLocatorType createImageLocatorType() {
		return new ImageLocatorType();
	}

	/**
	 * Create an instance of {@link IntegerDiagonalMatrixType }
	 * 
	 */
	public IntegerDiagonalMatrixType createIntegerDiagonalMatrixType() {
		return new IntegerDiagonalMatrixType();
	}

	/**
	 * Create an instance of {@link FloatMatrixType }
	 * 
	 */
	public FloatMatrixType createFloatMatrixType() {
		return new FloatMatrixType();
	}

	/**
	 * Create an instance of {@link SpectralCentroidType }
	 * 
	 */
	public SpectralCentroidType createSpectralCentroidType() {
		return new SpectralCentroidType();
	}

	/**
	 * Create an instance of
	 * {@link eu.prestoprime.model.ext.qa.AudioLLDScalarType.SeriesOfScalar }
	 * 
	 */
	public eu.prestoprime.model.ext.qa.AudioLLDScalarType.SeriesOfScalar createAudioLLDScalarTypeSeriesOfScalar() {
		return new eu.prestoprime.model.ext.qa.AudioLLDScalarType.SeriesOfScalar();
	}

	/**
	 * Create an instance of
	 * {@link eu.prestoprime.model.ext.qa.ScalableSeriesType.Scaling }
	 * 
	 */
	public eu.prestoprime.model.ext.qa.ScalableSeriesType.Scaling createScalableSeriesTypeScaling() {
		return new eu.prestoprime.model.ext.qa.ScalableSeriesType.Scaling();
	}

	/**
	 * Create an instance of {@link SpatioTemporalLocatorType.CoordRef }
	 * 
	 */
	public SpatioTemporalLocatorType.CoordRef createSpatioTemporalLocatorTypeCoordRef() {
		return new SpatioTemporalLocatorType.CoordRef();
	}

	/**
	 * Create an instance of {@link AudioSignalQualityType.ErrorEventList }
	 * 
	 */
	public AudioSignalQualityType.ErrorEventList createAudioSignalQualityTypeErrorEventList() {
		return new AudioSignalQualityType.ErrorEventList();
	}

	/**
	 * Create an instance of
	 * {@link eu.prestoprime.model.ext.qa.AudioLLDVectorType.SeriesOfVector }
	 * 
	 */
	public eu.prestoprime.model.ext.qa.AudioLLDVectorType.SeriesOfVector createAudioLLDVectorTypeSeriesOfVector() {
		return new eu.prestoprime.model.ext.qa.AudioLLDVectorType.SeriesOfVector();
	}

	/**
	 * Create an instance of {@link KeywordAnnotationType.Keyword }
	 * 
	 */
	public KeywordAnnotationType.Keyword createKeywordAnnotationTypeKeyword() {
		return new KeywordAnnotationType.Keyword();
	}

	/**
	 * Create an instance of
	 * {@link Spatial2DCoordinateSystemType.LocalCoordinateSystem }
	 * 
	 */
	public Spatial2DCoordinateSystemType.LocalCoordinateSystem createSpatial2DCoordinateSystemTypeLocalCoordinateSystem() {
		return new Spatial2DCoordinateSystemType.LocalCoordinateSystem();
	}

	/**
	 * Create an instance of
	 * {@link Spatial2DCoordinateSystemType.IntegratedCoordinateSystem }
	 * 
	 */
	public Spatial2DCoordinateSystemType.IntegratedCoordinateSystem createSpatial2DCoordinateSystemTypeIntegratedCoordinateSystem() {
		return new Spatial2DCoordinateSystemType.IntegratedCoordinateSystem();
	}

	/**
	 * Create an instance of {@link CreationType.CreationCoordinates }
	 * 
	 */
	public CreationType.CreationCoordinates createCreationTypeCreationCoordinates() {
		return new CreationType.CreationCoordinates();
	}

	/**
	 * Create an instance of {@link MelodySequenceType.NoteArray.Note }
	 * 
	 */
	public MelodySequenceType.NoteArray.Note createMelodySequenceTypeNoteArrayNote() {
		return new MelodySequenceType.NoteArray.Note();
	}

	/**
	 * Create an instance of
	 * {@link MelodySequenceType.StartingNote.StartingPitch.PitchNote }
	 * 
	 */
	public MelodySequenceType.StartingNote.StartingPitch.PitchNote createMelodySequenceTypeStartingNoteStartingPitchPitchNote() {
		return new MelodySequenceType.StartingNote.StartingPitch.PitchNote();
	}

	/**
	 * Create an instance of
	 * {@link MotionActivityType.SpatialDistributionParams }
	 * 
	 */
	public MotionActivityType.SpatialDistributionParams createMotionActivityTypeSpatialDistributionParams() {
		return new MotionActivityType.SpatialDistributionParams();
	}

	/**
	 * Create an instance of
	 * {@link MotionActivityType.SpatialLocalizationParams }
	 * 
	 */
	public MotionActivityType.SpatialLocalizationParams createMotionActivityTypeSpatialLocalizationParams() {
		return new MotionActivityType.SpatialLocalizationParams();
	}

	/**
	 * Create an instance of {@link ElectronicAddressType.Telephone }
	 * 
	 */
	public ElectronicAddressType.Telephone createElectronicAddressTypeTelephone() {
		return new ElectronicAddressType.Telephone();
	}

	/**
	 * Create an instance of {@link MediaQualityType.QualityRating }
	 * 
	 */
	public MediaQualityType.QualityRating createMediaQualityTypeQualityRating() {
		return new MediaQualityType.QualityRating();
	}

	/**
	 * Create an instance of {@link MediaQualityType.PerceptibleDefects }
	 * 
	 */
	public MediaQualityType.PerceptibleDefects createMediaQualityTypePerceptibleDefects() {
		return new MediaQualityType.PerceptibleDefects();
	}

	/**
	 * Create an instance of {@link RatingType.RatingScheme }
	 * 
	 */
	public RatingType.RatingScheme createRatingTypeRatingScheme() {
		return new RatingType.RatingScheme();
	}

	/**
	 * Create an instance of
	 * {@link eu.prestoprime.model.ext.qa.InlineTermDefinitionType.Name }
	 * 
	 */
	public eu.prestoprime.model.ext.qa.InlineTermDefinitionType.Name createInlineTermDefinitionTypeName() {
		return new eu.prestoprime.model.ext.qa.InlineTermDefinitionType.Name();
	}

	/**
	 * Create an instance of {@link MediaFormatType.BitRate }
	 * 
	 */
	public MediaFormatType.BitRate createMediaFormatTypeBitRate() {
		return new MediaFormatType.BitRate();
	}

	/**
	 * Create an instance of {@link MediaFormatType.AudioCoding.AudioChannels }
	 * 
	 */
	public MediaFormatType.AudioCoding.AudioChannels createMediaFormatTypeAudioCodingAudioChannels() {
		return new MediaFormatType.AudioCoding.AudioChannels();
	}

	/**
	 * Create an instance of {@link MediaFormatType.AudioCoding.Sample }
	 * 
	 */
	public MediaFormatType.AudioCoding.Sample createMediaFormatTypeAudioCodingSample() {
		return new MediaFormatType.AudioCoding.Sample();
	}

	/**
	 * Create an instance of {@link MediaFormatType.VisualCoding.Format }
	 * 
	 */
	public MediaFormatType.VisualCoding.Format createMediaFormatTypeVisualCodingFormat() {
		return new MediaFormatType.VisualCoding.Format();
	}

	/**
	 * Create an instance of {@link MediaFormatType.VisualCoding.Pixel }
	 * 
	 */
	public MediaFormatType.VisualCoding.Pixel createMediaFormatTypeVisualCodingPixel() {
		return new MediaFormatType.VisualCoding.Pixel();
	}

	/**
	 * Create an instance of {@link MediaFormatType.VisualCoding.Frame }
	 * 
	 */
	public MediaFormatType.VisualCoding.Frame createMediaFormatTypeVisualCodingFrame() {
		return new MediaFormatType.VisualCoding.Frame();
	}

	/**
	 * Create an instance of {@link PersonGroupType.Name }
	 * 
	 */
	public PersonGroupType.Name createPersonGroupTypeName() {
		return new PersonGroupType.Name();
	}

	/**
	 * Create an instance of {@link PersonGroupType.NameTerm }
	 * 
	 */
	public PersonGroupType.NameTerm createPersonGroupTypeNameTerm() {
		return new PersonGroupType.NameTerm();
	}

	/**
	 * Create an instance of {@link NonMixtureAmountOfMotionType.Fixed }
	 * 
	 */
	public NonMixtureAmountOfMotionType.Fixed createNonMixtureAmountOfMotionTypeFixed() {
		return new NonMixtureAmountOfMotionType.Fixed();
	}

	/**
	 * Create an instance of
	 * {@link eu.prestoprime.model.ext.qa.TermDefinitionBaseType.Name }
	 * 
	 */
	public eu.prestoprime.model.ext.qa.TermDefinitionBaseType.Name createTermDefinitionBaseTypeName() {
		return new eu.prestoprime.model.ext.qa.TermDefinitionBaseType.Name();
	}

	/**
	 * Create an instance of {@link OrganizationType.Name }
	 * 
	 */
	public OrganizationType.Name createOrganizationTypeName() {
		return new OrganizationType.Name();
	}

	/**
	 * Create an instance of {@link OrganizationType.NameTerm }
	 * 
	 */
	public OrganizationType.NameTerm createOrganizationTypeNameTerm() {
		return new OrganizationType.NameTerm();
	}

	/**
	 * Create an instance of {@link SpeakerInfoType.PhoneIndex.PhoneIndexEntry }
	 * 
	 */
	public SpeakerInfoType.PhoneIndex.PhoneIndexEntry createSpeakerInfoTypePhoneIndexPhoneIndexEntry() {
		return new SpeakerInfoType.PhoneIndex.PhoneIndexEntry();
	}

	/**
	 * Create an instance of {@link SpeakerInfoType.WordIndex.WordIndexEntry }
	 * 
	 */
	public SpeakerInfoType.WordIndex.WordIndexEntry createSpeakerInfoTypeWordIndexWordIndexEntry() {
		return new SpeakerInfoType.WordIndex.WordIndexEntry();
	}

	/**
	 * Create an instance of {@link WordLexiconType.Token }
	 * 
	 */
	public WordLexiconType.Token createWordLexiconTypeToken() {
		return new WordLexiconType.Token();
	}

	/**
	 * Create an instance of {@link CreationToolType.Setting }
	 * 
	 */
	public CreationToolType.Setting createCreationToolTypeSetting() {
		return new CreationToolType.Setting();
	}

	/**
	 * Create an instance of
	 * {@link eu.prestoprime.model.ext.qa.SegmentType.TextAnnotation }
	 * 
	 */
	public eu.prestoprime.model.ext.qa.SegmentType.TextAnnotation createSegmentTypeTextAnnotation() {
		return new eu.prestoprime.model.ext.qa.SegmentType.TextAnnotation();
	}

	/**
	 * Create an instance of {@link MotionTrajectoryType.CoordRef }
	 * 
	 */
	public MotionTrajectoryType.CoordRef createMotionTrajectoryTypeCoordRef() {
		return new MotionTrajectoryType.CoordRef();
	}

	/**
	 * Create an instance of {@link MotionTrajectoryType.CoordDef.Repr }
	 * 
	 */
	public MotionTrajectoryType.CoordDef.Repr createMotionTrajectoryTypeCoordDefRepr() {
		return new MotionTrajectoryType.CoordDef.Repr();
	}

	/**
	 * Create an instance of {@link PersonType.Affiliation }
	 * 
	 */
	public PersonType.Affiliation createPersonTypeAffiliation() {
		return new PersonType.Affiliation();
	}

	/**
	 * Create an instance of {@link KeyType.KeyNote }
	 * 
	 */
	public KeyType.KeyNote createKeyTypeKeyNote() {
		return new KeyType.KeyNote();
	}

	/**
	 * Create an instance of {@link ClassificationType.Genre }
	 * 
	 */
	public ClassificationType.Genre createClassificationTypeGenre() {
		return new ClassificationType.Genre();
	}

	/**
	 * Create an instance of {@link ClassificationType.CaptionLanguage }
	 * 
	 */
	public ClassificationType.CaptionLanguage createClassificationTypeCaptionLanguage() {
		return new ClassificationType.CaptionLanguage();
	}

	/**
	 * Create an instance of {@link ClassificationType.SignLanguage }
	 * 
	 */
	public ClassificationType.SignLanguage createClassificationTypeSignLanguage() {
		return new ClassificationType.SignLanguage();
	}

	/**
	 * Create an instance of {@link TemporalInterpolationType.WholeInterval }
	 * 
	 */
	public TemporalInterpolationType.WholeInterval createTemporalInterpolationTypeWholeInterval() {
		return new TemporalInterpolationType.WholeInterval();
	}

	/**
	 * Create an instance of {@link TemporalInterpolationType.KeyTimePoint }
	 * 
	 */
	public TemporalInterpolationType.KeyTimePoint createTemporalInterpolationTypeKeyTimePoint() {
		return new TemporalInterpolationType.KeyTimePoint();
	}

	/**
	 * Create an instance of
	 * {@link TemporalInterpolationType.InterpolationFunctions.KeyValue }
	 * 
	 */
	public TemporalInterpolationType.InterpolationFunctions.KeyValue createTemporalInterpolationTypeInterpolationFunctionsKeyValue() {
		return new TemporalInterpolationType.InterpolationFunctions.KeyValue();
	}

	/**
	 * Create an instance of {@link AvailabilityType.AvailabilityPeriod }
	 * 
	 */
	public AvailabilityType.AvailabilityPeriod createAvailabilityTypeAvailabilityPeriod() {
		return new AvailabilityType.AvailabilityPeriod();
	}

	/**
	 * Create an instance of {@link DominantColorType.Value }
	 * 
	 */
	public DominantColorType.Value createDominantColorTypeValue() {
		return new DominantColorType.Value();
	}

	/**
	 * Create an instance of {@link ParametricMotionType.CoordRef }
	 * 
	 */
	public ParametricMotionType.CoordRef createParametricMotionTypeCoordRef() {
		return new ParametricMotionType.CoordRef();
	}

	/**
	 * Create an instance of {@link ParametricMotionType.CoordDef }
	 * 
	 */
	public ParametricMotionType.CoordDef createParametricMotionTypeCoordDef() {
		return new ParametricMotionType.CoordDef();
	}

	/**
	 * Create an instance of {@link ColorSamplingType.Lattice }
	 * 
	 */
	public ColorSamplingType.Lattice createColorSamplingTypeLattice() {
		return new ColorSamplingType.Lattice();
	}

	/**
	 * Create an instance of {@link ColorSamplingType.Field.Component.Offset }
	 * 
	 */
	public ColorSamplingType.Field.Component.Offset createColorSamplingTypeFieldComponentOffset() {
		return new ColorSamplingType.Field.Component.Offset();
	}

	/**
	 * Create an instance of {@link ColorSamplingType.Field.Component.Period }
	 * 
	 */
	public ColorSamplingType.Field.Component.Period createColorSamplingTypeFieldComponentPeriod() {
		return new ColorSamplingType.Field.Component.Period();
	}

	/**
	 * Create an instance of
	 * {@link SpokenContentLatticeType.Block.Node.WordLink }
	 * 
	 */
	public SpokenContentLatticeType.Block.Node.WordLink createSpokenContentLatticeTypeBlockNodeWordLink() {
		return new SpokenContentLatticeType.Block.Node.WordLink();
	}

	/**
	 * Create an instance of
	 * {@link SpokenContentLatticeType.Block.Node.PhoneLink }
	 * 
	 */
	public SpokenContentLatticeType.Block.Node.PhoneLink createSpokenContentLatticeTypeBlockNodePhoneLink() {
		return new SpokenContentLatticeType.Block.Node.PhoneLink();
	}

	/**
	 * Create an instance of {@link RegionLocatorType.CoordRef }
	 * 
	 */
	public RegionLocatorType.CoordRef createRegionLocatorTypeCoordRef() {
		return new RegionLocatorType.CoordRef();
	}

	/**
	 * Create an instance of {@link RegionLocatorType.Box }
	 * 
	 */
	public RegionLocatorType.Box createRegionLocatorTypeBox() {
		return new RegionLocatorType.Box();
	}

	/**
	 * Create an instance of {@link RegionLocatorType.Polygon }
	 * 
	 */
	public RegionLocatorType.Polygon createRegionLocatorTypePolygon() {
		return new RegionLocatorType.Polygon();
	}

	/**
	 * Create an instance of {@link PlaceType.GeographicPosition }
	 * 
	 */
	public PlaceType.GeographicPosition createPlaceTypeGeographicPosition() {
		return new PlaceType.GeographicPosition();
	}

	/**
	 * Create an instance of {@link PlaceType.AdministrativeUnit }
	 * 
	 */
	public PlaceType.AdministrativeUnit createPlaceTypeAdministrativeUnit() {
		return new PlaceType.AdministrativeUnit();
	}

	/**
	 * Create an instance of {@link PlaceType.PostalAddress }
	 * 
	 */
	public PlaceType.PostalAddress createPlaceTypePostalAddress() {
		return new PlaceType.PostalAddress();
	}

	/**
	 * Create an instance of {@link PlaceType.StructuredPostalAddress }
	 * 
	 */
	public PlaceType.StructuredPostalAddress createPlaceTypeStructuredPostalAddress() {
		return new PlaceType.StructuredPostalAddress();
	}

	/**
	 * Create an instance of {@link PlaceType.StructuredInternalCoordinates }
	 * 
	 */
	public PlaceType.StructuredInternalCoordinates createPlaceTypeStructuredInternalCoordinates() {
		return new PlaceType.StructuredInternalCoordinates();
	}

	/**
	 * Create an instance of {@link ContourShapeType.Peak }
	 * 
	 */
	public ContourShapeType.Peak createContourShapeTypePeak() {
		return new ContourShapeType.Peak();
	}

	/**
	 * Create an instance of {@link VisualImpairmentType.Relevance }
	 * 
	 */
	public VisualImpairmentType.Relevance createVisualImpairmentTypeRelevance() {
		return new VisualImpairmentType.Relevance();
	}

	/**
	 * Create an instance of {@link DropoutLevelType.Area }
	 * 
	 */
	public DropoutLevelType.Area createDropoutLevelTypeArea() {
		return new DropoutLevelType.Area();
	}

	/**
	 * Create an instance of {@link DropoutLevelType.SubsequentFrames }
	 * 
	 */
	public DropoutLevelType.SubsequentFrames createDropoutLevelTypeSubsequentFrames() {
		return new DropoutLevelType.SubsequentFrames();
	}

	/**
	 * Create an instance of
	 * {@link DropoutDefectType.ReplacedByDropoutCompensation }
	 * 
	 */
	public DropoutDefectType.ReplacedByDropoutCompensation createDropoutDefectTypeReplacedByDropoutCompensation() {
		return new DropoutDefectType.ReplacedByDropoutCompensation();
	}

	/**
	 * Create an instance of {@link DropoutDefectType.AffectedArea.Lines }
	 * 
	 */
	public DropoutDefectType.AffectedArea.Lines createDropoutDefectTypeAffectedAreaLines() {
		return new DropoutDefectType.AffectedArea.Lines();
	}

	/**
	 * Create an instance of {@link WowFlutterDefectType.RelativeDetune }
	 * 
	 */
	public WowFlutterDefectType.RelativeDetune createWowFlutterDefectTypeRelativeDetune() {
		return new WowFlutterDefectType.RelativeDetune();
	}

	/**
	 * Create an instance of
	 * {@link FlickerLevelType.FrequencyDistribution.FlickerIntensity }
	 * 
	 */
	public FlickerLevelType.FrequencyDistribution.FlickerIntensity createFlickerLevelTypeFrequencyDistributionFlickerIntensity() {
		return new FlickerLevelType.FrequencyDistribution.FlickerIntensity();
	}

	/**
	 * Create an instance of {@link ColorRangeDefectType.Channel.SaturatedArea }
	 * 
	 */
	public ColorRangeDefectType.Channel.SaturatedArea createColorRangeDefectTypeChannelSaturatedArea() {
		return new ColorRangeDefectType.Channel.SaturatedArea();
	}

	/**
	 * Create an instance of {@link LineScratchDefectType.ScratchProperties }
	 * 
	 */
	public LineScratchDefectType.ScratchProperties createLineScratchDefectTypeScratchProperties() {
		return new LineScratchDefectType.ScratchProperties();
	}

	/**
	 * Create an instance of {@link BlurLevelType.EdgeLoss }
	 * 
	 */
	public BlurLevelType.EdgeLoss createBlurLevelTypeEdgeLoss() {
		return new BlurLevelType.EdgeLoss();
	}

	/**
	 * Create an instance of
	 * {@link ChannelMisalignmentType.HorizontalDisplacement }
	 * 
	 */
	public ChannelMisalignmentType.HorizontalDisplacement createChannelMisalignmentTypeHorizontalDisplacement() {
		return new ChannelMisalignmentType.HorizontalDisplacement();
	}

	/**
	 * Create an instance of
	 * {@link ChannelMisalignmentType.VerticalDisplacement }
	 * 
	 */
	public ChannelMisalignmentType.VerticalDisplacement createChannelMisalignmentTypeVerticalDisplacement() {
		return new ChannelMisalignmentType.VerticalDisplacement();
	}

	/**
	 * Create an instance of {@link NoiseGrainLevelType.DominantFrequency }
	 * 
	 */
	public NoiseGrainLevelType.DominantFrequency createNoiseGrainLevelTypeDominantFrequency() {
		return new NoiseGrainLevelType.DominantFrequency();
	}

	/**
	 * Create an instance of
	 * {@link NoiseGrainLevelType.BrightnessDependency.GrainIntensity }
	 * 
	 */
	public NoiseGrainLevelType.BrightnessDependency.GrainIntensity createNoiseGrainLevelTypeBrightnessDependencyGrainIntensity() {
		return new NoiseGrainLevelType.BrightnessDependency.GrainIntensity();
	}

	/**
	 * Create an instance of {@link ImageInstabilityType.HorizontalDisplacement }
	 * 
	 */
	public ImageInstabilityType.HorizontalDisplacement createImageInstabilityTypeHorizontalDisplacement() {
		return new ImageInstabilityType.HorizontalDisplacement();
	}

	/**
	 * Create an instance of {@link ImageInstabilityType.VerticalDisplacement }
	 * 
	 */
	public ImageInstabilityType.VerticalDisplacement createImageInstabilityTypeVerticalDisplacement() {
		return new ImageInstabilityType.VerticalDisplacement();
	}

	/**
	 * Create an instance of {@link DustLevelType.NumberOfSpots }
	 * 
	 */
	public DustLevelType.NumberOfSpots createDustLevelTypeNumberOfSpots() {
		return new DustLevelType.NumberOfSpots();
	}

	/**
	 * Create an instance of {@link DustLevelType.Area }
	 * 
	 */
	public DustLevelType.Area createDustLevelTypeArea() {
		return new DustLevelType.Area();
	}

	/**
	 * Create an instance of {@link DustLevelType.Size }
	 * 
	 */
	public DustLevelType.Size createDustLevelTypeSize() {
		return new DustLevelType.Size();
	}

	/**
	 * Create an instance of {@link DustLevelType.AverageIntensity }
	 * 
	 */
	public DustLevelType.AverageIntensity createDustLevelTypeAverageIntensity() {
		return new DustLevelType.AverageIntensity();
	}

	/**
	 * Create an instance of {@link UpconversionType.ChracteristicResolution }
	 * 
	 */
	public UpconversionType.ChracteristicResolution createUpconversionTypeChracteristicResolution() {
		return new UpconversionType.ChracteristicResolution();
	}

	/**
	 * Create an instance of {@link BlockingLevelType.BlockEdgeIntensity }
	 * 
	 */
	public BlockingLevelType.BlockEdgeIntensity createBlockingLevelTypeBlockEdgeIntensity() {
		return new BlockingLevelType.BlockEdgeIntensity();
	}

	/**
	 * Create an instance of {@link ChannelListType.Channel }
	 * 
	 */
	public ChannelListType.Channel createChannelListTypeChannel() {
		return new ChannelListType.Channel();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "Scale", scope = TextureBrowsingType.class)
	public JAXBElement<String> createTextureBrowsingTypeScale(String value) {
		return new JAXBElement<String>(_TextureBrowsingTypeScale_QNAME, String.class, TextureBrowsingType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "Direction", scope = TextureBrowsingType.class)
	public JAXBElement<String> createTextureBrowsingTypeDirection(String value) {
		return new JAXBElement<String>(_TextureBrowsingTypeDirection_QNAME, String.class, TextureBrowsingType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link NameComponentType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "GivenName", scope = PersonNameType.class)
	public JAXBElement<NameComponentType> createPersonNameTypeGivenName(NameComponentType value) {
		return new JAXBElement<NameComponentType>(_PersonNameTypeGivenName_QNAME, NameComponentType.class, PersonNameType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link NameComponentType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "Salutation", scope = PersonNameType.class)
	public JAXBElement<NameComponentType> createPersonNameTypeSalutation(NameComponentType value) {
		return new JAXBElement<NameComponentType>(_PersonNameTypeSalutation_QNAME, NameComponentType.class, PersonNameType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link NameComponentType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "FamilyName", scope = PersonNameType.class)
	public JAXBElement<NameComponentType> createPersonNameTypeFamilyName(NameComponentType value) {
		return new JAXBElement<NameComponentType>(_PersonNameTypeFamilyName_QNAME, NameComponentType.class, PersonNameType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link NameComponentType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "LinkingName", scope = PersonNameType.class)
	public JAXBElement<NameComponentType> createPersonNameTypeLinkingName(NameComponentType value) {
		return new JAXBElement<NameComponentType>(_PersonNameTypeLinkingName_QNAME, NameComponentType.class, PersonNameType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "Numeration", scope = PersonNameType.class)
	public JAXBElement<String> createPersonNameTypeNumeration(String value) {
		return new JAXBElement<String>(_PersonNameTypeNumeration_QNAME, String.class, PersonNameType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link NameComponentType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "Title", scope = PersonNameType.class)
	public JAXBElement<NameComponentType> createPersonNameTypeTitle(NameComponentType value) {
		return new JAXBElement<NameComponentType>(_PersonNameTypeTitle_QNAME, NameComponentType.class, PersonNameType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}
	 * {@link BigInteger }{@code >}{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "SrcPixel", scope = Spatial2DCoordinateSystemType.LocalCoordinateSystem.class)
	public JAXBElement<List<BigInteger>> createSpatial2DCoordinateSystemTypeLocalCoordinateSystemSrcPixel(List<BigInteger> value) {
		return new JAXBElement<List<BigInteger>>(_Spatial2DCoordinateSystemTypeLocalCoordinateSystemSrcPixel_QNAME, ((Class) List.class), Spatial2DCoordinateSystemType.LocalCoordinateSystem.class, ((List<BigInteger>) value));
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}
	 * {@link Float }{@code >}{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "CoordPoint", scope = Spatial2DCoordinateSystemType.LocalCoordinateSystem.class)
	public JAXBElement<List<Float>> createSpatial2DCoordinateSystemTypeLocalCoordinateSystemCoordPoint(List<Float> value) {
		return new JAXBElement<List<Float>>(_Spatial2DCoordinateSystemTypeLocalCoordinateSystemCoordPoint_QNAME, ((Class) List.class), Spatial2DCoordinateSystemType.LocalCoordinateSystem.class, ((List<Float>) value));
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}
	 * {@link BigInteger }{@code >}{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "Pixel", scope = Spatial2DCoordinateSystemType.LocalCoordinateSystem.class)
	public JAXBElement<List<BigInteger>> createSpatial2DCoordinateSystemTypeLocalCoordinateSystemPixel(List<BigInteger> value) {
		return new JAXBElement<List<BigInteger>>(_Spatial2DCoordinateSystemTypeLocalCoordinateSystemPixel_QNAME, ((Class) List.class), Spatial2DCoordinateSystemType.LocalCoordinateSystem.class, ((List<BigInteger>) value));
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}
	 * {@link BigInteger }{@code >}{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "urn:mpeg:mpeg7:schema:2004", name = "CurrPixel", scope = Spatial2DCoordinateSystemType.LocalCoordinateSystem.class)
	public JAXBElement<List<BigInteger>> createSpatial2DCoordinateSystemTypeLocalCoordinateSystemCurrPixel(List<BigInteger> value) {
		return new JAXBElement<List<BigInteger>>(_Spatial2DCoordinateSystemTypeLocalCoordinateSystemCurrPixel_QNAME, ((Class) List.class), Spatial2DCoordinateSystemType.LocalCoordinateSystem.class, ((List<BigInteger>) value));
	}

}
