//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PercussiveInstrumentTimbreType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PercussiveInstrumentTimbreType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}AudioDSType">
 *       &lt;sequence>
 *         &lt;element name="LogAttackTime" type="{urn:mpeg:mpeg7:schema:2004}LogAttackTimeType"/>
 *         &lt;element name="SpectralCentroid" type="{urn:mpeg:mpeg7:schema:2004}SpectralCentroidType"/>
 *         &lt;element name="TemporalCentroid" type="{urn:mpeg:mpeg7:schema:2004}TemporalCentroidType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PercussiveInstrumentTimbreType", propOrder = { "logAttackTime", "spectralCentroid", "temporalCentroid" })
public class PercussiveInstrumentTimbreType extends AudioDSType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "LogAttackTime", required = true)
	protected LogAttackTimeType logAttackTime;
	@XmlElement(name = "SpectralCentroid", required = true)
	protected SpectralCentroidType spectralCentroid;
	@XmlElement(name = "TemporalCentroid", required = true)
	protected TemporalCentroidType temporalCentroid;

	/**
	 * Gets the value of the logAttackTime property.
	 * 
	 * @return possible object is {@link LogAttackTimeType }
	 * 
	 */
	public LogAttackTimeType getLogAttackTime() {
		return logAttackTime;
	}

	/**
	 * Sets the value of the logAttackTime property.
	 * 
	 * @param value
	 *            allowed object is {@link LogAttackTimeType }
	 * 
	 */
	public void setLogAttackTime(LogAttackTimeType value) {
		this.logAttackTime = value;
	}

	/**
	 * Gets the value of the spectralCentroid property.
	 * 
	 * @return possible object is {@link SpectralCentroidType }
	 * 
	 */
	public SpectralCentroidType getSpectralCentroid() {
		return spectralCentroid;
	}

	/**
	 * Sets the value of the spectralCentroid property.
	 * 
	 * @param value
	 *            allowed object is {@link SpectralCentroidType }
	 * 
	 */
	public void setSpectralCentroid(SpectralCentroidType value) {
		this.spectralCentroid = value;
	}

	/**
	 * Gets the value of the temporalCentroid property.
	 * 
	 * @return possible object is {@link TemporalCentroidType }
	 * 
	 */
	public TemporalCentroidType getTemporalCentroid() {
		return temporalCentroid;
	}

	/**
	 * Sets the value of the temporalCentroid property.
	 * 
	 * @param value
	 *            allowed object is {@link TemporalCentroidType }
	 * 
	 */
	public void setTemporalCentroid(TemporalCentroidType value) {
		this.temporalCentroid = value;
	}

}
