//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PitchShiftDefectType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PitchShiftDefectType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}ErrorEventType">
 *       &lt;sequence>
 *         &lt;element name="RelativeDetune" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PitchShiftDefectType", namespace = "http://www.prestospace.org/res/defect_quality", propOrder = { "relativeDetune" })
public class PitchShiftDefectType extends ErrorEventType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "RelativeDetune")
	protected float relativeDetune;

	/**
	 * Gets the value of the relativeDetune property.
	 * 
	 */
	public float getRelativeDetune() {
		return relativeDetune;
	}

	/**
	 * Sets the value of the relativeDetune property.
	 * 
	 */
	public void setRelativeDetune(float value) {
		this.relativeDetune = value;
	}

}
