//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RelationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RelationType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}DSType">
 *       &lt;attribute name="type" use="required" type="{urn:mpeg:mpeg7:schema:2004}termReferenceListType" />
 *       &lt;attribute name="target" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:mpeg:mpeg7:schema:2004}termReferenceListType">
 *             &lt;length value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="directed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="strength" type="{urn:mpeg:mpeg7:schema:2004}zeroToOneType" default="1.0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationType")
public class RelationType extends DSType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlAttribute(name = "type", required = true)
	protected List<String> type;
	@XmlAttribute(name = "target", required = true)
	protected List<String> target;
	@XmlAttribute(name = "directed")
	protected Boolean directed;
	@XmlAttribute(name = "strength")
	protected Float strength;

	/**
	 * Gets the value of the type property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the type property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getType().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getType() {
		if (type == null) {
			type = new ArrayList<String>();
		}
		return this.type;
	}

	/**
	 * Gets the value of the target property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the target property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTarget().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getTarget() {
		if (target == null) {
			target = new ArrayList<String>();
		}
		return this.target;
	}

	/**
	 * Gets the value of the directed property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isDirected() {
		if (directed == null) {
			return true;
		} else {
			return directed;
		}
	}

	/**
	 * Sets the value of the directed property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setDirected(Boolean value) {
		this.directed = value;
	}

	/**
	 * Gets the value of the strength property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public float getStrength() {
		if (strength == null) {
			return 1.0F;
		} else {
			return strength;
		}
	}

	/**
	 * Sets the value of the strength property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setStrength(Float value) {
		this.strength = value;
	}

}
