//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SegmentDecompositionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SegmentDecompositionType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}DSType">
 *       &lt;attribute name="criteria" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="(([a-zA-Z][0-9a-zA-Z+\-\.]*:)?/{0,2}[0-9a-zA-Z;/\?:@&amp;=\+$\.\-_!~\*'\(\)%]+)?(#[0-9a-zA-Z;/\?:@&amp;=\+$\.\-_!~\*'\(\)%]+)?"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="overlap" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="gap" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SegmentDecompositionType")
@XmlSeeAlso({ SpatialSegmentDecompositionType.class, MediaSourceSegmentDecompositionType.class, TemporalSegmentDecompositionType.class, SpatioTemporalSegmentDecompositionType.class })
public abstract class SegmentDecompositionType extends DSType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlAttribute(name = "criteria", required = true)
	protected String criteria;
	@XmlAttribute(name = "overlap")
	protected Boolean overlap;
	@XmlAttribute(name = "gap")
	protected Boolean gap;

	/**
	 * Gets the value of the criteria property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCriteria() {
		return criteria;
	}

	/**
	 * Sets the value of the criteria property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCriteria(String value) {
		this.criteria = value;
	}

	/**
	 * Gets the value of the overlap property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isOverlap() {
		if (overlap == null) {
			return false;
		} else {
			return overlap;
		}
	}

	/**
	 * Sets the value of the overlap property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setOverlap(Boolean value) {
		this.overlap = value;
	}

	/**
	 * Gets the value of the gap property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isGap() {
		if (gap == null) {
			return false;
		} else {
			return gap;
		}
	}

	/**
	 * Sets the value of the gap property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setGap(Boolean value) {
		this.gap = value;
	}

}
