//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SilenceHeaderType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SilenceHeaderType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpeg7:schema:2004}HeaderType">
 *       &lt;attribute name="minDuration" use="required" type="{urn:mpeg:mpeg7:schema:2004}mediaDurationType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SilenceHeaderType")
public class SilenceHeaderType extends HeaderType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlAttribute(name = "minDuration", required = true)
	protected String minDuration;

	/**
	 * Gets the value of the minDuration property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMinDuration() {
		return minDuration;
	}

	/**
	 * Sets the value of the minDuration property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMinDuration(String value) {
		this.minDuration = value;
	}

}
