//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.24 at 11:42:28 PM CEST 
//

package eu.prestoprime.model.ext.qa;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for UpconversionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="UpconversionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prestospace.org/res/defect_quality}VisualImpairmentType">
 *       &lt;sequence>
 *         &lt;element name="ChracteristicResolution">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpconversionType", namespace = "http://www.prestospace.org/res/defect_quality", propOrder = { "chracteristicResolution" })
public class UpconversionType extends VisualImpairmentType implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "ChracteristicResolution", required = true)
	protected UpconversionType.ChracteristicResolution chracteristicResolution;

	/**
	 * Gets the value of the chracteristicResolution property.
	 * 
	 * @return possible object is
	 *         {@link UpconversionType.ChracteristicResolution }
	 * 
	 */
	public UpconversionType.ChracteristicResolution getChracteristicResolution() {
		return chracteristicResolution;
	}

	/**
	 * Sets the value of the chracteristicResolution property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link UpconversionType.ChracteristicResolution }
	 * 
	 */
	public void setChracteristicResolution(UpconversionType.ChracteristicResolution value) {
		this.chracteristicResolution = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
	 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class ChracteristicResolution implements Serializable {

		private final static long serialVersionUID = 1L;
		@XmlAttribute(name = "width")
		@XmlSchemaType(name = "nonNegativeInteger")
		protected BigInteger width;
		@XmlAttribute(name = "height")
		@XmlSchemaType(name = "nonNegativeInteger")
		protected BigInteger height;

		/**
		 * Gets the value of the width property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getWidth() {
			return width;
		}

		/**
		 * Sets the value of the width property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setWidth(BigInteger value) {
			this.width = value;
		}

		/**
		 * Gets the value of the height property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getHeight() {
			return height;
		}

		/**
		 * Sets the value of the height property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setHeight(BigInteger value) {
			this.height = value;
		}

	}

}
